### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by VikramTiwari** [GoogleCloudPlatform/DataflowTemplates#1]
Since Dataflow supports both Java and Python, it's misleading to name it as just DataflowTemplates and only keep Java examples in there.

I suggest that it should use the preferred nomenclature of `DataflowTemplates-Java` the same way `google-cloud` SDK does.

I can help add some templates for python. Here's a sample directory which I have been keeping some samples in: https://github.com/VikramTiwari/dataflow-samples

PS: I know, even I am guilty of not using proper nomenclature, but I am not Google :)

**Comment by sabhyankar** [comment]
This repository now supports both Python and Java templates (via the v2 - Flex templates).

**Comment by pabloem** [comment]
hi @VikramTiwari ! consdider adding your samples to https://github.com/pabloem/awesome-beam/  via a pull request : )
