### ISSUE TITLE
CDC Template - add support for MySQL TINYINT data type.

### ISSUE THREAD

**Issue by nikie** [GoogleCloudPlatform/DataflowTemplates#101]
Hi, @pabloem,

Thank your for a wonderful [Dataflow CDC Template](https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/cdc-parent)!

When exploring it for MySQL tables ingestion, I faced an issue - [cdc-embedded-connector](https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/cdc-parent/cdc-embedded-connector) fails on startup when trying to push schema to Data Catalog if a whitelisted table contains MySQL TINYINT columns. 

This occurs because `FIELD_TYPE_NAMES` mapping in [SchemaUtils.java](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/v2/cdc-parent/cdc-common/src/main/java/com/google/cloud/dataflow/cdc/common/SchemaUtils.java#L38) misses INT16 Beam schema type, which represents TINYINT coming from MYSQL.

I am submitting PR with a fix.
Thanks

**Comment by pabloem** [comment]
Thanks!
