### ISSUE TITLE
TextIOToBigQuery IO error for nested schema

### ISSUE THREAD

**Issue by meet-marakana** [GoogleCloudPlatform/DataflowTemplates#104]
I wanted to use a nested schema for BigQuery table. As mentioned in here..

https://cloud.google.com/bigquery/docs/nested-repeated

I have to use fields in the BigQuery Schema. but as here in the source code, we can see that there's no handling of the fields. please help me for this issue. can I use Auto-detect for the schema? If yes then tell me how? need your help as early as possible.

**Comment by wtait1-ff** [comment]
Looks like this can be resolved as a duplicate of https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/8?
