### ISSUE TITLE
Improve handling of NUMERIC/DECIMAL, Time and Timestamp in CDC solution

### ISSUE THREAD

**Issue by pabloem** [GoogleCloudPlatform/DataflowTemplates#108]
Currently, these types are converted like so:

- `NUMERIC`/`DECIMAL` are converted to `STRING` in BigQuery
- `Time` is converted into milliseconds from midnight
- `Timestamp` is converted into milliseconds since epoch

**Comment by damienhollis** [comment]
@pabloem any idea when these improvements will be made, we would like to use this solution but these limitations are holding us back?

**Comment by pabloem** [comment]
oops - only NUMERIC is handled as of right now. Time and Timestamp are still remaining.
