### ISSUE TITLE
Support for tables without primary keys

### ISSUE THREAD

**Issue by alenfrantz** [GoogleCloudPlatform/DataflowTemplates#111]
The schema returned from the Cloud SQL is showing up as NULL. Attaching screenshot for the same. This is causing issue while storing schema in the data catalog.
<img width="741" alt="Debizium error" src="https://user-images.githubusercontent.com/12842444/80936973-da28dd00-8df0-11ea-86e1-97ea109d7bf6.png">

Steps done so far:
1. Created Cloud SQL database and tables with sample data.
2. Created Pub/Sub Topics.
3. Executed the connector via source (as per given steps): mvn exec:java -pl cdc-embedded-connector \
    -Dexec.args="path/to/your/properties/file.properties [path/to/password/file.properties]"
4. Inserted few records in Cloud SQL - MySql database. 

Could someone please help, I can provide further required information.

**Comment by pabloem** [comment]
Thanks for trying out the connector!

Is this causing the connector to error out? Is the schema in data catalog
not showing up?

Is the pipeline unable to start?

I'll look at the log tomorrow morning and get back to you.

**Comment by pabloem** [comment]
Ah I believe the issue is that your table does not have a primary key. The
template 'needs' a primary key to create a replica table. Can you try by
adding a primary key to your table?

Also, if you would like the template to support tables without primary
keys, please let me know.

**Comment by ibmggn** [comment]
Hi Pablo,

I was facing the same issue as well. I haven't tested with Primary Key yet though. However practically there will be many tables and many of them won't have primary key. In that case I would like to see how your solution can help.

See if you can update the source and make it work.

Thanks !

**Comment by pabloem** [comment]
Thanks @siddjava ! I'll work on that, but consider that if there is no primary key for the table, then it is not possible to do MERGE-type statements to produce a replica table. The only output would be a table containing a list of all the changes applied to the table. Is that something that you can work with?

**Comment by siddjava** [comment]
> Thanks @siddjava ! I'll work on that, but consider that if there is no primary key for the table, then it is not possible to do MERGE-type statements to produce a replica table. The only output would be a table containing a list of all the changes applied to the table. Is that something that you can work with?

That should be okay, as I am thinking of a use case where certain tables will have just incremental data without updates, which I can move them to BigQuery

**Comment by pabloem** [comment]
okay, that sounds fine! I've renamed the issue, and will work on this soon. Thanks @siddjava !

**Comment by alenfrantz** [comment]
Thanks for the quick reply.
Yes.
Connector is not getting error out. 
Schema is not showing up in data catalog. 
Pipeline is unable to start.

A template to support tables without primary key should be helpful as there are many cases where the table does not have a PK.

**Comment by siddjava** [comment]
> okay, that sounds fine! I've renamed the issue, and will work on this soon. Thanks @siddjava !

Thanks @pabloem Appreciate your efforts on this !

**Comment by pabloem** [comment]
I've added https://github.com/GoogleCloudPlatform/DataflowTemplates/commit/ee75366512033e7dea2ede3e14f930896dc09c87 to enable the connector to publish change data for tables without primary keys.

**Comment by pabloem** [comment]
Thanks for your interest all.

FYI @griscz @alenfrantz @siddjava
