### ISSUE TITLE
[Bug]: MongoDB to bigquery jobs with connection string in plain text on the console 

### ISSUE THREAD

**Issue by dcarvalhal** [GoogleCloudPlatform/DataflowTemplates#1136]
### Related Template(s)

mongodb_to_bigquery_cdc

### What happened?

When creating mongodb jobs for bigquery, the template does not give the option to use the secret manager to query the connection string to connect to Mongodb. So, starting the job the way it is, the connection string is exposed in the console. This is a serious security issue.

### Beam Version

Newer than 2.46.0

**Comment by bvolpato** [comment]
Addressed by https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1134

Thanks for reporting!
