### ISSUE TITLE
[Bug]: Can't use wildcard in mqtt topic

### ISSUE THREAD

**Issue by ryry6** [GoogleCloudPlatform/DataflowTemplates#1152]
### Related Template(s)

mqtt-to-pubsub

### What happened?

The regex validation for the mqtt input topic is preventing the use of wildcards e.g. topic/#

### Beam Version

Newer than 2.46.0

**Comment by laurigates** [comment]
This issue is still relevant. Not supporting wildcards makes this template quite limited.
