### ISSUE TITLE
What is my Mysql Instance name?

### ISSUE THREAD

**Issue by lucaslizama** [GoogleCloudPlatform/DataflowTemplates#117]
For the cdc-parent template

The documentation says that topics must be [prefix][instance].[database].[table]. I'm running the connector image in my local machine with a local mysql database in another docker container, the connector is connected to the database, it gives me this message:

`Logger Binding: org.slf4j.impl.Log4jLoggerFactory@224edc67
org.slf4j.impl.Log4jLoggerFactory
May 11, 2020 2:46:10 PM com.github.shyiko.mysql.binlog.BinaryLogClient connect
INFO: Connected to 172.17.0.2:3306 at mysql-bin.000001/2691 (sid:5550, cid:46)`

I've tried creating the topics in my GCP project but had no luck receiving any message in my subcription, what is the correct topic name in my case?

**Comment by pabloem** [comment]
were you able to figure this one out? @lucaslizama 

I will soon push support for running on a single pubsub topic, and this will make this part of the solution much easier.

**Comment by lucaslizama** [comment]
> were you able to figure this one out? @lucaslizama
> 
> I will soon push support for running on a single pubsub topic, and this will make this part of the solution much easier.

No, I had to create a cloud instance of Mysql to have an instance name. CDC worked ok after that, but how exactly would you connect a not GCP hosted Mysql database to the connector?

**Comment by heromanba** [comment]
> > were you able to figure this one out? @lucaslizama
> > I will soon push support for running on a single pubsub topic, and this will make this part of the solution much easier.
> 
> No, I had to create a cloud instance of Mysql to have an instance name. CDC worked ok after that, but how exactly would you connect a not GCP hosted Mysql database to the connector?

Hello, have you found a way to connect local mysql? I still cannot figure this out. Thanks!
