### ISSUE TITLE
In whitelistedTables configration, what is ${instance}?

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/DataflowTemplates#120]
whitelistedTables=...
These tables should have their names fully qualified ${instance}.${database}.${table}.

MySql

**Comment by pabloem** [comment]
can you add some detail to your question?

**Comment by mario-yapp** [comment]
I have the same question. 
I have a AWS RDS MySQL Endpoint. Is this the instance that is required: ${instance}.${database}.${table}.
whitelistedTables=myrdsendpoint.db.table
Is correct?

**Comment by chetansharmagithub** [comment]
@ghost @ryanmcdowell @pabloem  @mario-yapp 
Here is an update:
Use your database name as the instance name.
I've got it working by using my database name as the instance name. 
For example, if my database name is **rdw** and table name is **people**, then my whitelistedTables string for this table will be **rdw.rdw.people**
I hope this helps everyone here.
