### ISSUE TITLE
Connector listening but not acting

### ISSUE THREAD

**Issue by smoms** [GoogleCloudPlatform/DataflowTemplates#121]
i am using the code version. These are the properties:

databaseName=test001
databaseUsername=root
databaseAddress=localhost
databasePassword=xxx
gcpProject=xxxx
gcpPubsubTopicPrefix=export_demo_
whitelistedTables=MySQL80.test001.customer

Connector starts:
INFO: Connected to localhost:3306 at log-bin.000006/234 (sid:6003, cid:14)

but nothing happen when i insert data in DB.
Topic name: export_demo_MySQL80.test001.customer

**Comment by Mati539** [comment]
Did you manage to solve that problem?

**Comment by smoms** [comment]
no

**Comment by griscz** [comment]
Hey @smoms, does all your data have PKs? 
One of the other topics on the CDC label has a similar case where the problem was that some of the tables don't have PK, and without them there is not a way to perform the merge at the end. 

Check this conversation: https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/111

**Comment by pabloem** [comment]
ah quite sorry about missing this. : (

**Comment by pabloem** [comment]
Have you seen any stack traces on the connector side?

**Comment by dzoellner** [comment]
Also running into this issue, connecting just fine but no pubsub events being created on table updates. 

No stack traces on the connector side.

**Comment by grontorino** [comment]
I ran into the same problem，no more  info showed after connecting to Cloud sql instance. I'm sure my table have PK and pub/sub config is correct.

**Comment by grontorino** [comment]
@pabloem there no stack traces on the connector side:
Aug 04, 2020 7:02:03 AM com.github.shyiko.mysql.binlog.BinaryLogClient connect
INFO: Connected to cloudsql_host:3306 at a64e-42010a800048:1-86506 (sid:6185, cid:38096)

I use the `Deploying as a Docker Container from Source` node, my properties:
databaseName=crm
databaseUsername=debezium
databaseAddress=instance host
databasePort=3306
gcpProject=project
gcpPubsubTopicPrefix=cdc
whitelistedTables=test.crm.crm_test
databasePassword=debezium
databaseManagementSystem=mysql

I try to modify the configuration options of the database, will throw a connection error, so the Cloud Sql connection is normal. But change the gcp‘s config don't work, the service start and no more info. 
Is there any good solutions?

**Comment by frodriguezf** [comment]
Hi. Debugging the whitelist vs the tablename I found that they never matches.

https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/v2/cdc-parent/cdc-embedded-connector/src/main/java/com/google/cloud/dataflow/cdc/connector/PubSubChangeConsumer.java#L117

I added a System.out like this:

```
System.out.println("checking if table is whitelisted. tablename: " + tableName);
System.out.println("checking if table is whitelisted. whitelistedTables: " + String.join(",", whitelistedTables));

if (whitelistedTables.contains(tableName)) {

```

And it logged out something like:

```
checking if table is whitelisted. whitelistedTables: instance.db.table                                                                   
checking if table is whitelisted. tablename: db.db.table 
```

So I changed the whitelistedTables parameters:
`whitelistedTables=db.db.table`

and it works. I can't tell anymore so far, hope it helps.

Regards

**Comment by chetansharmagithub** [comment]
Here is an update:
Use your database name as the instance name.
I've got it working by using my database name as the instance name. For example, if my database name is **rdw** and table name is **people**, then my whitelistedTables string for this table will be **rdw.rdw.people**

So, for the question above by @smoms , here is the working solution
whitelistedTables=test001.test001.customer

I hope this helps everyone here.
