### ISSUE TITLE
Security concern: Pub/Sub to Splunk HEC requires a token as a parameter in plain text

### ISSUE THREAD

**Issue by brandonjbjelland** [GoogleCloudPlatform/DataflowTemplates#122]
## What's the issue?

The pub/sub to splunk beta dataflow recently announced in [this blog post](https://cloud.google.com/blog/products/data-analytics/connect-to-splunk-with-a-dataflow-template) ([docs here](https://cloud.google.com/dataflow/docs/guides/templates/provided-streaming#cloudpubsubtosplunk)) has a bit of a security gap in that it requires a plain text `token` as input. Code for getting that token [is here](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/src/main/java/com/google/cloud/teleport/templates/PubSubToSplunk.java#L249). I know the team considers security a top priority so I'm hoping there's a known stopgap solution. Without some way to hide this param, anyone with viewer access across the service, project, or org would likely have visibility to this token - not ideal.

## Alternative solutions

Some potential workarounds and expected behavior:

1. Dataflow job integration directly with KMS or secrets manager - much in the way cloudbuild can decrypt a secret as an initial step defined in the build template, it would be slick if dataflow had a similar capability, pointing to pre-existing secrets that are automatically injected into the run context at job start. e.g. the SA running a dataflow job has a decrypter role to a KMS key. `sensitiveParameters.foo` specifies 2 attributes - a KMS key ID and the corresponding ciphertext - upon job launch, decryption happens automatically, with the raw contents of the secret available as environment variable `foo`.
2. Instead of the `token` parameter, the template could instead require a secret manager secret version ID and attempt to fetch that secret as an initial step in the job. [This post](https://medium.com/google-cloud/using-google-cloud-key-management-service-with-dataflow-templates-71924f0f841f) takes a similar approach using KMS. This is slightly different than #1 in that it isn't a feature request to dataflow the product, just a change to the relevant template.

Though I haven't used these myself, I've asked around and heard some transforms provide KMS integration e.g. bigqueryio support a `withKmsKey`. I wonder if there's a pattern that can be reused from that. +@melbrodrigues for input.

**Comment by sabhyankar** [comment]
Hi @brandonjbjelland - Thanks for pointing this out. We are looking to implement option#2 very similar to the implementation in [blog](https://medium.com/google-cloud/using-google-cloud-key-management-service-with-dataflow-templates-71924f0f841f) that you linked. 

I will keep this issue open for now for tracking purposes.

**Comment by sabhyankar** [comment]
@melbrodrigues 
Can you take a stab at implementing this similar to how we added this capability in the [Jdbc template](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/src/main/java/com/google/cloud/teleport/templates/JdbcToBigQuery.java)?

**Comment by melbrodrigues** [comment]
This would be a neat addition to the template! I'll start working on this soon.
