### ISSUE TITLE
Please support Node.JS / Javascript

### ISSUE THREAD

**Issue by wholenews** [GoogleCloudPlatform/DataflowTemplates#126]
Creating placeholder issue (upvote if important to you) for Javascript / Typescript support.  Needless to say this issue is hugely important to myself and others.

I understand BEAM support is needed (Upvote here https://issues.apache.org/jira/browse/BEAM-1754 ).  But as GCP customer, I'm looking to Google rather than Apache BEAM, to provide Node.JS support for Dataflow.  Thanks!

**Comment by sabhyankar** [comment]
Is this related to a specific Dataflow Template pipeline in this repo? If not, and if this is a general feature request for Dataflow, I would suggest opening a FR [here].(https://cloud.google.com/support/docs/issue-trackers#trackers-list)

**Comment by wholenews** [comment]
Thanks. Filed there instead.
