### ISSUE TITLE
Auto-scaling performance issues when compiling Google-provided template with Maven

### ISSUE THREAD

**Issue by AAB87** [GoogleCloudPlatform/DataflowTemplates#129]
I am using ``GCS_Text_to_BigQuery`` batch pipeline template to launch a Dataflow task using the latest compilation available on GCS (gs://dataflow-templates/latest/GCS_Text_to_BigQuery) and the performance is as expected (10-15 minutes processing 600M records using a n1-standard-16 machine).

However, testing the pipeline with the same code compiled by me using Maven the results are very different respect the ones using the compiled template provided by Google on GCS: auto-scaling seems not to be working in a proper way (the increase of workers during the task is very low and the process is taking much more time, in addition the % CPU consumption of the workers is very low).

I compiled the template with the following command as indicated in your README file (compilation is successful):
```bash
mvn compile exec:java \
-Dexec.mainClass=com.google.cloud.teleport.templates.TextIOToBigQuery \
-Dexec.cleanupDaemonThreads=false \
-Dexec.args=" \
--project=<gcp-project-id> \
--stagingLocation=gs://<gcs-bucket>/staging \
--tempLocation=gs://<gcs-bucket>/temp \
--templateLocation=gs://<gcs-bucket>/templates/text-io-to-bq.json \
--runner=DataflowRunner"
``` 

I am launching the task using the python API, with exactly the same parameters using Google-provided template on GCS or my own one:
```python
from googleapiclient.discovery import build

dataflow = build('dataflow', 'v1b3', cache_discovery=False)

# Compilation of template provided by Google on GCS (performance OK)
# dataflow_template = 'gs://dataflow-templates/latest/GCS_Text_to_BigQuery'

# Compilation of the same template build by me (performance NOK)
dataflow_template = 'gs://<gcs-bucket>/templates/text-io-to-bq.json'

parameters = {
    'javascriptTextTransformFunctionName': '<udf-function>',
    'JSONPath': 'gs://<gcs-bucket>/resources/schemas/<bq-schema-file>',
    'javascriptTextTransformGcsPath': 'gs://<gcs-bucket>/resources/UDF/<udf-file>',
    'inputFilePattern': 'gs://<gcs-bucket>/data/*',
    'outputTable': '<gcp-project>:<bq-dataset>.<bq-table>',
    'bigQueryLoadingTemporaryDirectory': 'gs://<gcs-bucket>/bq_temp_location/'
}

environment = {
    'tempLocation': 'gs://<gcs-bucket>/temp',
    'machineType': 'n1-standard-16'
}

request = dataflow.projects().locations().templates().launch(
    projectId='<gcp-project-id>',
    gcsPath=dataflow_template,
    location='<location>',
    body={
        'jobName': '<job-name>',
        'parameters': parameters,
        'environment': environment
    }
)

response = request.execute()
```

Any ideas on what could be the cause of this difference? Any support from your side would be really appreciated. Thanks in advance.

**Comment by jaketf** [comment]
When you run this pipeline does anything actually happen?
The symptoms of no autoscaling + low cpu seems like it's starting a job but nothing is getting executed. 
Are there any suspicious worker / shuffler logs in StackDriver ?

This line looks problematic:
```python3
dataflow_template = 'gs://<gcs-bucket>/templates/text-io-to-bq.json'
```

The [public docs](https://cloud.google.com/dataflow/docs/guides/templates/creating-templates#metadata) on creating templates call out that these json files should not end in `.json` extension. I'm not sure where this restriction comes from.

**Comment by AlonsoAndradeBlazquez** [comment]
Hello @jaketf , thanks a lot for your prompt response.

It seems that the recommendation that you pointed out is concerning the metadata file that you can optionally write with your template, in my case I did not create any metadata file.

Anyway I tried to follow this guideline also for the template file itself, so I replaced this line in the Maven command:
```bash
--templateLocation=gs://<gcs-bucket>/templates/text-io-to-bq.json \
```
by this one:
```bash
--templateLocation=gs://<gcs-bucket>/templates/GCS_Text_to_BigQuery \
```

Also, I replaced this line for the python API call:
```python
# Compilation of the same template build by me (performance NOK)
dataflow_template = 'gs://<gcs-bucket>/templates/text-io-to-bq.json'
```
by this one:
```python
# Compilation of the same template build by me (performance NOK)
dataflow_template = 'gs://<gcs-bucket>/templates/GCS_Text_to_BigQuery'
```

With those modifications the results are the same in terms of autoscaling, % consumption:
- Using Google-provided template from GCS:
![image](https://user-images.githubusercontent.com/31450795/82885237-2b864100-9f45-11ea-8546-4c3998ceab6c.png)
![image](https://user-images.githubusercontent.com/31450795/82885252-34771280-9f45-11ea-9614-a29a4ddb2990.png)
![image](https://user-images.githubusercontent.com/31450795/82885269-39d45d00-9f45-11ea-8984-a654f1bf0b00.png)

- Using Google-provided template compiled by me:
![image](https://user-images.githubusercontent.com/31450795/82884918-ba468e00-9f44-11ea-9803-7105ef514cdc.png)
![image](https://user-images.githubusercontent.com/31450795/82885089-f1b53a80-9f44-11ea-9eff-902b0937734e.png)
![image](https://user-images.githubusercontent.com/31450795/82885119-fd086600-9f44-11ea-8fd6-305d76a5cd1b.png)

Concerning the task, I took a look for example to the BigQuery temp directory on GCS and the parsed items to be inserted in the table were being recorded there. I did not see any warning or error at the task / workers log records, apart from the different information regarding the number of workers, autoscaling, etc between the two options. Everything seems to be working as far as I can see, but much more slow in the case of my own compilation of the template.

**Comment by sabhyankar** [comment]
How many entries do you see for the logger value of "System.err" in the self-compiled template vs the Google Provided Template? Also can you confirm that you are compiling and running at the same SDK level (2.20.0) as the current Google Provided Template? The github code could be at a higher version level than the released code.

I would look at the following:
* Are SDK levels the same?
* Are we using the same machine type?
* Are we using the same JavaScript UDF (if any)?
* How fast is the backlog clearing in both the variants?
* Is there more excessive logging in one of the variants (not sure why that would be the case)?

Note that logging is a synchronous action and would lead to lower throughput and utilization.

**Comment by AlonsoAndradeBlazquez** [comment]
Hello @sabhyankar , thanks a lot for your support and sorry for my late response.

Concerning your questions:

> Also can you confirm that you are compiling and running at the same SDK level (2.20.0) as the current Google Provided Template? The github code could be at a higher version level than the released code.

My compilation of the template also uses SDK 2.20.0.:
- Displayed on task details UI on task info:
![image](https://user-images.githubusercontent.com/31450795/83031059-6915c780-a034-11ea-91a6-9a856c3fb903.png)
- Displayed within my compiled template json file:
```json
{
    "environment" : {
        "sdkPipelineOptions" : {
             "options" : {
                 "userAgent" : "Apache_Beam_SDK_for_Java/2.20.0(JDK_11_environment)",
                 ...
             },
             ...
        },
        ...
    },
    ...
}
```

> I would look at the following:
> 
> * Are SDK levels the same?

Yes (answered above).

> * Are we using the same machine type?
> * Are we using the same JavaScript UDF (if any)?

Yes to both. I use, for my compilation or Google-provided one:
- the same machine (n1-standard-16 machine)
- the same custom UDF with functions to manage the parsing of each line of the files.

All the data in ``parameters``, ``environment``, ``projectId`` and ``location`` in the python API call below are always the same for the two options, I only change ``gcsPath`` with my template or Google-provided one and ``jobName``:
```python
from googleapiclient.discovery import build

dataflow = build('dataflow', 'v1b3', cache_discovery=False)

# Compilation of template provided by Google on GCS (performance OK)
# dataflow_template = 'gs://dataflow-templates/latest/GCS_Text_to_BigQuery'

# Compilation of the same pipeline build by me (performance NOK)
dataflow_template = 'gs://<gcs-bucket>/templates/GCS_Text_to_BigQuery'

parameters = {
    'javascriptTextTransformFunctionName': '<udf-function>',
    'JSONPath': 'gs://<gcs-bucket>/resources/schemas/<bq-schema-file>',
    'javascriptTextTransformGcsPath': 'gs://<gcs-bucket>/resources/UDF/<udf-file>',
    'inputFilePattern': 'gs://<gcs-bucket>/data/*',
    'outputTable': '<gcp-project>:<bq-dataset>.<bq-table>',
    'bigQueryLoadingTemporaryDirectory': 'gs://<gcs-bucket>/bq_temp_location/'
}

environment = {
    'tempLocation': 'gs://<gcs-bucket>/temp',
    'machineType': 'n1-standard-16'
}

request = dataflow.projects().locations().templates().launch(
    projectId='<gcp-project-id>',
    gcsPath=dataflow_template,
    location='<location>',
    body={
        'jobName': '<job-name>',
        'parameters': parameters,
        'environment': environment
    }
)

response = request.execute()
```

> How many entries do you see for the logger value of "System.err" in the self-compiled template vs the Google Provided Template?

In my own compilation, I saw a few messages related to System.err:
![image](https://user-images.githubusercontent.com/31450795/84383363-6c8c7f80-abec-11ea-9ba3-f3878ed27a54.png)

```console
{
 jsonPayload: {
  logger: "System.err"   
  message: "Warning: Nashorn engine is planned to be removed from a future JDK release"   
  stage: "s18"   
  step: "JavascriptTextTransformer.TransformTextViaJavascript/ParDo(Anonymous)"   
  thread: "27"     
 }
 resource: {
  labels: {
   step_id: "JavascriptTextTransformer.TransformTextViaJavascript/ParDo(Anonymous)"    
  }
  type: "dataflow_step"   
 }
 severity: "ERROR"  
}
```
```console
{
 insertId: "10932729737278405:18240:0:91699"  
 jsonPayload: {
  logger: "System.err"   
  message: "Please use a logger instead of System.out or System.err.
Please switch to using org.slf4j.Logger.
See: https://cloud.google.com/dataflow/pipelines/logging"   
  stage: "s18"   
  step: "JavascriptTextTransformer.TransformTextViaJavascript/ParDo(Anonymous)"   
  thread: "27"   
 }
 resource: {
  type: "dataflow_step"   
 }
 severity: "WARNING"  
}
```
In Google-provided one, I did not see any log related to System.err:

> * How fast is the backlog clearing in both the variants?

Could you kindly specify how can I check this?

> * Is there more excessive logging in one of the variants (not sure why that would be the case)?

Please find below an histogram comparison including all log levels and all dataflow log names from Stackdriver:
- *Own compilation of Google-provided template*
![image](https://user-images.githubusercontent.com/31450795/84377767-7362c480-abe3-11ea-82f9-ab9a199e809a.png)
- *Google-provided template*
![image](https://user-images.githubusercontent.com/31450795/84378111-ebc98580-abe3-11ea-84ed-e8e4ef9ab762.png)

Concerning the job-message logs,  I saw this kind of messages in my own compilation that don't appear for google-provided template:
```console
{
 insertId: "nb9pmuc2zj"  
 labels: {…}  
 resource: {…}  
 severity: "DEBUG"  
 textPayload: "Resized worker pool to 6, though goal was 8.  This could be a quota issue."  
}
```

Additionally, I don't know if the fact that the files to be parsed are compressed in .gz can be an issue for autoscaling according to what is written in this docs [section](https://cloud.google.com/dataflow/docs/guides/deploying-a-pipeline#autoscaling) (I try to parse the same compressed files in the same bucket folder for the two options but there is no issue in Google-provided template).

Thanks again in advance for your support.

**Comment by sabhyankar** [comment]
> "userAgent" : "Apache_Beam_SDK_for_Java/2.20.0(JDK_11_environment)",

Hi @AAB87 - Can you recompile with JDK 8 and see if the behavior changes :)

**Comment by AAB87** [comment]
Hi @sabhyankar now it works! Sorry, I did not realized that that specific Java version was required for the compilation :S :S

Thanks a lot for your help :)
