### ISSUE TITLE
Publishing Template

### ISSUE THREAD

**Issue by justanhnt** [GoogleCloudPlatform/DataflowTemplates#13]
Just pulling project & publish this by mvn command:
`mvn compile exec:java \
-Dexec.mainClass=com.google.cloud.teleport.templates.PubsubToAvro \
-Dexec.cleanupDaemonThreads=false \
-Dexec.args=" \
--project=${gcp_project_id} \
--stagingLocation=gs://${bucket_name}/staging \
--tempLocation=gs://${bucket_name}/temp \
--templateLocation=gs://${bucket_name}/templates/default-pubsub-to-avro.json \
--runner=DataflowRunner"`

and create a job with default template from Dataflow & see that warning:
> No metadata file found for this template.

**Comment by bvolpato** [comment]
We have made several changes to the process. Please check https://github.com/GoogleCloudPlatform/DataflowTemplates#developingcontributing-templates

This issue was stale for some time. Please reopen it if there is a follow up or any related questions.
