### ISSUE TITLE
add support for nested and repeated fields in auto-mapper

### ISSUE THREAD

**Issue by bjoernrost** [GoogleCloudPlatform/DataflowTemplates#130]
I have been tinkering with the v2/pubsub-cdc-to-bigquery template. This would be more useful (at least to me) if the auto-mapper was able to handle nested objects and arrays in incoming json to map to records and repeated fields in BQ.

In my mind, all of these cases and any combination of them should be supported:

Flat json (this works today)
`{"k1": "scalar"}`

A json array should be mapped to a REPEATED field in BQ
`{"k2": ["array_elem1","array_elem2"]}`

A json object should map to a RECORD type
`{"k3": {"id": "1", "type": "object"}}`

Arrays of objects should map to REPEATED RECORD
`{"k4": [{"id": "1", "type": "object1"},{"id": "2", "type": "object2"}]}`

All but the first example fail today. They just create a new field of type string. The actual insert of the record fails (I think due to mismatch of record and schema) and the record is also not written to the deadletter table.

**Comment by bjoernrost** [comment]
I started on this and have a working prototype that passes all the above cases and also objects nested within other objects. Will clean that up and create a PR.

`{"k1": "scalar", "k2": ["array_elem1","array_elem2"],"k3": {"id": "1", "type": "object"}, "k4": [{"id": "1", "type": "object1"}, {"id": "2", "type": "object2"}], "k5": {"name": "nest", "n1": [{"type": "object", "text": "hello"},{"type": "object", "text": "world"}]}}
`

**Comment by sabhyankar** [comment]
@dhercher

**Comment by dhercher** [comment]
Hi Bjorn,

Please see the response in [Issue 132](https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/132) as I believe these are roughly the same issue and should have a consistent fix.

Record and array types can often cause more issues as they come from JSON and can switch interchangeably in this sort of use-case.  I would opt to default to String still (with proper handling of these fields) and allow record/array data types via configuration as specified in the other ticket.  Hopefully this aligns with your needs here

**Comment by bjoernrost** [comment]
Yup, the issues are somewhat related, and I have [code that is almost ready to be cleaned up for a PR](https://github.com/bjoernrost/DataflowTemplates/tree/bjoern).

I saw the idea of implementing this by overriding getInputSchema but I couldn't quite wrap my head around how that would work, so I added the logic directly to the mapper. I agree that some of that behaviour may make sense to enable/disable via a config.

Checking for the type of a field turned out to be easy for bool, int, record. Obviously with the caveat that we may be unlucky and only "see" an int value in the first record that adds the field and then there may be strings after. That's why it would be better to have a proper schema in the first place. A config switch for "safe" mode and "best effort" may make sense.

My code also picks up arrays and nested records but it only checks for new fields at the top-level, if the top-level item is a record it needs to recurse into that and check for new fields there.

**Comment by dhercher** [comment]
Hi Bjorn,

Just wanted to let you know the fix to properly clean bool, record, or array types which are mapped to String in BigQuery is now pushed.  I'll leave this issue open to discuss the changes you've been developing and close out the other issue since it will be covered here.

**Comment by pabloem** [comment]
I'll close this out now, but please feel free to reopen if there's anything else to discuss.
