### ISSUE TITLE
MySQL's CDC to BigQuery - Queries

### ISSUE THREAD

**Issue by aravindanck** [GoogleCloudPlatform/DataflowTemplates#131]
I was going through the repo on MySQL's CDC -> BQ using Debezium and Cloud dataflow. 
https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/cdc-parent

I've not gone through the code yet, have a couple of questions - would be great if you could answer them:

1) I thought there's no order guarantee in a PubSub topic. how do you manage to capture the change logs from MySQL In order in a PubSub topic?
2) How frequent do you write data from Cloud Dataflow to the temp table (change log table) and then MERGE it? Asking this because, isn't there a quota limit to the number of writes that you can perform on single table per day?

**Comment by pabloem** [comment]
Thanks @aravindanck - answering:

> 1. I thought there's no order guarantee in a PubSub topic. how do you manage to capture the change logs from MySQL In order in a PubSub topic?

Data is streamed to the changelog table out of order. We use the timestamp in each row to apply changes in the merge. Does that make sense?

> 2. How frequent do you write data from Cloud Dataflow to the temp table (change log table) and then MERGE it? Asking this because, isn't there a quota limit to the number of writes that you can perform on single table per day?

You're right! the lmit was 1000 merges per table per day when I wrote the code. By default we issue a merge query every 5 minutes, but you can pass a parameter to choose the frequency.

**Comment by aravindanck** [comment]
So, from the changelog table you do a 5 min window query to order the data inside the window before a merge? 
How do you keep track of the window start and end timestamps in a reliable way?

**Comment by pabloem** [comment]
The template issues a MERGE query every 5 minutes. This query is not windowed. The query scans the whole changelog table, and gets the latest change for each primary key. The timestamps come from the binlog in MySQL.

LMK if that makes sense

**Comment by aravindanck** [comment]
Is it good to scan the entire changelog table in BQ every 5 mins?
Thought doing it in windows or since the last processed timestamp would be an efficient approach.

**Comment by pabloem** [comment]
There are two optimizations that we're thinking of applying here:

1. Issue merges only when there's data been pushed to the table

2. Use partitioned tables, to restrict the size of the merge.

I'll work on those sometime in the future.

**Comment by pabloem** [comment]
Closing this for now @aravindanck please lmk if you'd like to reopen and discuss further!
