### ISSUE TITLE
field auto-map to STRING breaks inserts of booleans

### ISSUE THREAD

**Issue by bjoernrost** [GoogleCloudPlatform/DataflowTemplates#132]
I am working on/with the automatic table mapper in v2/pubsub-cdc-to-bigquery. Whenever it comes across a new field in the source json, the target BQ table is extended with a new field of type STRING. One would think that this is safe because "everything" can be stored in a string. 
It turns out that BQ cannot cast boolean types to STRING, so when ingesting this valid piece of json:

`{"b1": true, "b2": false}`

it results in this error on ingestion:

`{"errors":[{"debugInfo":"","location":"b2","message":"Conversion from bool to std::string is unsupported.","reason":"invalid"}],"index":0}`

I think that we can test to see if we can cast to bool at the time we are adding the field and change the type to BOOLEAN in BQ instead of STRING.

**Comment by sabhyankar** [comment]
@dhercher

**Comment by dhercher** [comment]
Hi Björn,
    I agree this needs to be addressed.  For both of your issues I see these dividing into two separate items.  

    First, the mapper logic needs to clean data as a final step by comparing it to the chosen BigQuery column type and ensuring a best attempt to align the values.  Since the mapper defaults to String, this means String types are the primary focus (other types would be purposefully chosen so if they were chosen wrong that's less a bug than an incorrect directive).  I consider this first item to be a bug and I'm working on a short term fix.  Long term this cleanup logic will become its own class and be optionally applied.

    Second, what you are suggesting is mapping according to the type of the object rather than defaulting to String.  The mapper is intended to be easily extended, though I can see value for adding this as an optional configuration which can be set.  Currently I'm working on allowing a user to submit a schema file via gcs to be applied to the data.  I'll make a todo or happily accept a PR for the logic to apply types intelligently rather than just String if you have it.  This option has always slightly worried me since "smart" schema choices can often be more headache than they're worth.

    I'll followup once the change to stringify booleans (when the BigQuery column is a strong) is merged and released.

   Best,
      Dylan

**Comment by dhercher** [comment]
Hi Björn,

   We are discussing options for automatically mapping typed objects according to their type rather than to String by default in [Issue 130](https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/130).  I'll continue that conversation there.  The initial issue of bool's failing to load because bool->string fails is now resolved for Bool, Record, and Array's which are mapped to String.  I'm going to close this issue out since its now resolved and long term functionality is being followed up in 130.

  Best,
     Dylan
