### ISSUE TITLE
[Feature Request]: Improve Spanner Change Stream To BigQuery error messaging

### ISSUE THREAD

**Issue by damondouglas** [GoogleCloudPlatform/DataflowTemplates#1351]
### Related Template(s)

Spanner_Change_Streams_to_BigQuery

### What feature(s) are you requesting?

The output of this task is to provide actionable error reporting within [FailsafeModJsonToTableRowTransformer](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/FailsafeModJsonToTableRowTransformer.java)'s context.

When `FailsafeModJsonToTableRowFn` in [FailsafeModJsonToTableRowTransformer](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/FailsafeModJsonToTableRowTransformer.java) invokes private method `modJsonStringToTableRow` it will try/catch in a generic `Exception`, concatenating `Exception::getMessage` which is nullable. Some users report the following in their logs: `Caught exception when processing element , storing into dead letter queue. null`

A fix may consider more specific Exception catches and diagnose/remediate why getMessage is null. Additionally, the error message could reference where the dead letter records are stored, based on `deadLetterQueueDirectory` or its default value when not provided.

**Comment by pradeepnr** [comment]
Hi @damondouglas , can you point me to the nightly build which has this code changes? Thanks.
