### ISSUE TITLE
How do I increase Dataflow task memory if I use this template?

### ISSUE THREAD

**Issue by tavakolik** [GoogleCloudPlatform/DataflowTemplates#149]
We are using the Spanner to AVRO template for a large database, and DEADLINE_EXCEEDED is what we get before job completes, usually after 5 or 6 hours of churning. We know how to add workers, but we are capped due to other projects needing the horse power, how do we add memory to the job if it is shufflebound?

**Comment by tavakolik** [comment]
BTW, this was tried with sdk 2.2.0 after fixes were applied to it in the past few days. Also perhaps is there a way to change the timeout deadline for workers?

**Comment by bvolpato** [comment]
A good way to add more memory resources to a specific DoFn/transform would be to use [Dataflow Prime](https://cloud.google.com/dataflow/docs/guides/enable-dataflow-prime), but we are not doing it yet.

Perhaps a good way of handling it at this time is to customize the "Worker Machine Type" to use a larger instance. Maybe using one of the `highmem` GCE instances will do what you described ("how do we add memory to the job") as you can increase the memory without adding more vCPUs.
