### ISSUE TITLE
Dataflow UDF support for Node.js based code

### ISSUE THREAD

**Issue by ds185359** [GoogleCloudPlatform/DataflowTemplates#150]
Hi,

 I'm trying to write a javascript function that will do some data transformations for data received from pub/sub topic and then put it in BigQuery. However, I have a javascript proto file dependency. Thus, I will need to require or import some dependencies in this transformation script which will make it node.js based code. I see that when I upload this code, I get errors for require/imports because Dataflow UDF is expecting vanilla js. I couldn't find any relevant documentation that helps me use node.js based code for Dataflow UDF. So my questions are - do we support node.js based code for Dataflow UDF? If yes, where can I find relevant documentation for the same? If not, any work around or alternate options?

Thank you.

**Comment by prathapreddy123** [comment]
Currently only plain Javascript UDF's are supported

**Comment by llermaly** [comment]
Hello @prathapreddy123 , does this article apply for Dataflow UDF as well, and how to implement it?

https://medium.com/analytics-vidhya/using-npm-library-in-google-bigquery-udf-8aef01b868f4
