### ISSUE TITLE
V2 Flex Templates maven module compilation is failing 

### ISSUE THREAD

**Issue by davidolorundare** [GoogleCloudPlatform/DataflowTemplates#153]
#### Context

In the maven compilation step of v2/ Flex Template modules, the `compile` command fails. 

The maven-based compilation is used in the image build and package step for most of the Flex Templates. For instance [in the Pubsub binary to BigQuery template](https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/pubsub-binary-to-bigquery#compiling-the-pipeline), [the BigQuery to Paraquet template](https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/bigquery-to-parquet#building-container-image), [the Kafka to BigQuery template](https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/kafka-to-bigquery#building-container-image), and several others. The `compile` command failing results in that build/package step not completing and prevents creation of the container image needed in other execution steps of the templates.

#### Compiling the [PubSub binary to BigQuery pipeline](https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/kafka-to-bigquery#building-container-image)

Cloning the DataflowTemplates repo, navigating to the v2/ directory and running `mvn clean compile -pl pubsub-binary-to-bigquery -am` fails with the following error:

```
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module /home/dolorundare/dataflow-templates/DataflowTemplates/v2/datastream-to-bigquery of /home/dolorundare/dataflow-templates/DataflowTemplates/v2/pom.xml does not exist @
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.google.cloud.teleport.v2:dynamic-templates:1.0-SNAPSHOT (/home/dolorundare/dataflow-templates/DataflowTemplates/v2/pom.xml) has 1 error
[ERROR]     Child module /home/dolorundare/dataflow-templates/DataflowTemplates/v2/datastream-to-bigquery of /home/dolorundare/dataflow-templates/DataflowTemplates/v2/pom.xml does not exist
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

Screenshot of this error ![here](https://github.com/davidolorundare/flex-template-images/blob/master/FlexTemplateCompilationError.png)

#### Issue Fix

The parent pom file `DataflowTemplates/v2/pom.xml` lists `DataflowTemplates/v2/datastream-to-bigquery` as part of the modules, as seen [here](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/v2/pom.xml#L575). 
However, this module does not exist in the `v2/` directory, and this is resulting in the compliation errors seen earlier. 
The **suggested fix** is to remove the `<module>datastream-to-bigquery</module>` entry of the `pom.xml` file in the `v2/` directory. 

Removing this entry enables the compilation to proceed successfully. As seen ![here](https://github.com/davidolorundare/flex-template-images/blob/master/FlexTemplateCompliationFix-1.png) and ![here](https://github.com/davidolorundare/flex-template-images/blob/master/FlexTemplateCompliationFix-1.png) 

**Submitted [PR 153](https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/154) implements this fix**.

**Comment by sabhyankar** [comment]
This is now resolved.
