### ISSUE TITLE
CDC - Supporting latest version of Debezium

### ISSUE THREAD

**Issue by hallaji** [GoogleCloudPlatform/DataflowTemplates#165]
Hi 👋

I am wondering will you be supporting/upgrading Debezium to the latest version sometime?  

We're testing CDC to synchronise a PostgreSQL database to Bigquery. The current version of Debezium has been set to `0.9.5.Final`.

However, we can't benefit from the `pgoutput` plugin in PostgreSQL which requires at least `0.10.0`. 

On the other hand, we have some [hyper tables](https://docs.timescale.com/latest/introduction/architecture) which won't be synced until we upgrade Debezium to `1.0.*`. 

In addition, probably because of compatibility issues, I get this error on connector for `1.1+`.

```
v2/cdc-parent/cdc-embedded-connector
/src/main/java/com/google/cloud/dataflow/cdc/connector/PubSubChangeConsumer.java:

com.google.cloud.dataflow.cdc.connector.PubSubChangeConsumer is not abstract and does not override abstract 
method handleBatch(java.util.List<org.apache.kafka.connect.source.SourceRecord>, 
io.debezium.engine.DebeziumEngine.RecordCommitter<org.apache.kafka.connect.source.SourceRecord>) 
in io.debezium.engine.DebeziumEngine.ChangeConsumer

PubSubChangeConsumer.java method does not override or implement a method from a supertype
```

**Comment by pabloem** [comment]
I am sorry. I don'thave time to make this upgrade unfortunately.

On the good news, a new DebeziumIO transform is being added to Apache Beam, so you can consume changes from Debezium (including postgres) with your Beam pipeline. I will work to add other transforms, such as the BigQuery merges
