### ISSUE TITLE
CDC - Replica Queries Are Expensive

### ISSUE THREAD

**Issue by 3jerde** [GoogleCloudPlatform/DataflowTemplates#167]
Currently for CDC i see a problem for large tables as full table scans are being performed on every merge, both on the source (change log) and destination (replica). If the table is growing by a gigabytes daily this can suddenly get very expensive.

1. A solution is to have an updated timestamp in the destination table (or a log table) and then only pickup new data from the source table. We'd also have the BQ tables created with partitions/clusters on the PK and timestamp.

2. In the meantime I think it would be useful to easily disable the replica queries from being deployed.

3. Furthermore, I find it would be useful to have something like a dry run option that will create the BigQuery tables but will not acknowledge a message and will not start loading data. That way it would be easy recreating the bq tables with partitions and or clustering as one sees fit.

**Comment by andreasholmesberge** [comment]
Solution 2 is available in PR https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/168

**Comment by damienhollis** [comment]
I am seeing the same issue. In our case the source data is currently not changing and we are still paying the cost of querying the change log and replicating the latest change (at least, I think that's what is happening).

I think the idea of a table tracking the latest timestamp for each source table and partitioning on the timestamp in the change log would mostly resolve this issue.  Would this be a workable solution?

**Comment by krattan406** [comment]
> Solution 2 is available in PR #168

@andreasholmesberge, were you able to find a solution to the calls to merges even when there were no changes to the data?

**Comment by mycaule** [comment]
Hi, if you want to improve the code of the `MergeStatementBuiderFn`, I would just suggest adding a `WHERE DATE(timestamp )> CURRENT_DATE()-1` for the `source_table`, assuming it is partionned using the correct create disposition.
