### ISSUE TITLE
About enabling Streaming Engine in Pub / Sub Subscription to BigQuery templates

### ISSUE THREAD

**Issue by ca-kamiya-joji** [GoogleCloudPlatform/DataflowTemplates#171]
I'd like to enable Streaming Engine *1 in the Pub / Sub Subscription to BigQuery template *2, but it doesn't seem to be possible at this time. Can you add a function?

*1 https://cloud.google.com/dataflow/docs/guides/deploying-a-pipeline#streaming-engine
*2 https://cloud.google.com/dataflow/docs/guides/templates/provided-streaming#pubsub-topic-to-bigquery

**Comment by bvolpato** [comment]
It is now possible to enable Streaming Engine on any template job.

https://cloud.google.com/sdk/gcloud/reference/dataflow/flex-template/run#--enable-streaming-engine

https://cloud.google.com/sdk/gcloud/reference/dataflow/jobs/run#--enable-streaming-engine


Or from the UI:
![image](https://user-images.githubusercontent.com/3207647/216883381-af7cbc62-f0ee-4eac-9a47-a3770d8508eb.png)
