### ISSUE TITLE
Streaming Data Generator > Pub/Sub to BQ: 

### ISSUE THREAD

**Issue by mehrannazir** [GoogleCloudPlatform/DataflowTemplates#177]
I am using the [streaming data generator](https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/streaming-data-generator) to create JSON blobs. I then create a separate Pub/Sub to BQ pipeline using the output of the Streaming Data Generator.

When I write to BQ, I see an error: Failed to serialize json to table row.

I believe that this is similar to the error reported [here](https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/44), but since the payload is created from the streaming data generator pipeline, I have little control over the input to the P/S to BQ pipeline. Can this be a feature request?

**Comment by prathapreddy123** [comment]
Can you please share Schema used to generate fake messages and the sample output message generated that is failing while writing to BQ.

**Comment by prathapreddy123** [comment]
This template is enhanced to support writing directly to BigQuery
