### ISSUE TITLE
Kafka to BigQuery Dataflow - Error

### ISSUE THREAD

**Issue by matheusjerico** [GoogleCloudPlatform/DataflowTemplates#179]
I am trying to execute this example (https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/kafka-to-bigquery), but i am having a error.

```bash
gcloud beta dataflow flex-template run ${JOB_NAME} \
  --project=${PROJECT} --region=us-central1 \
  --template-file-gcs-location=${TEMPLATE_IMAGE_SPEC} \
  --parameters ^~^outputTableSpec=${OUTPUT_TABLE}~inputTopics=${TOPICS}~javascriptTextTransformGcsPath=${JS_PATH}~javascriptTextTransformFunctionName=${JS
_FUNC_NAME}~bootstrapServers=${BOOTSTRAP}

**ERROR**: (gcloud.beta.dataflow.flex-template.run) INVALID_ARGUMENT: (d7bdedd43c26b738): Docker image not specified in the template file.
```

my environment variable  TEMPLATE_IMAGE_SPEC is "gs://my-bucket-name/images/kafka-to-bigquery-image-spec.json" and the kafka-to-bigquery-image-spec.json content is: 
```bash
{
  "docker_template_spec": {
    "docker_image": "gcr.io/<project-id>/<image-name>"
  }
}
```

I didn't put tag after <image-name>.

**Comment by prathapreddy123** [comment]
@matheusjerico - Can you create the .json file in the format as specified in https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/streaming-data-generator as the specification is changed

**Comment by abramjstamper** [comment]
Even with the change, I believe it's still missing the `BootstrapServers` value from the link you attached.

Also for others who stumble upon this, note that the template @prathapreddy123 attached uses `topic`. The Kafka-to-BigQuery code base expects `inputTopics`.

**Comment by bvolpato** [comment]
Any reason to not use the already-built Dataflow Templates?

More specifically, we release a new version roughly every week: `gs://dataflow-templates/latest/flex/Kafka_to_BigQuery`.

If you need to change/rebuild the template, I encourage using the new Templates Plugin: https://github.com/GoogleCloudPlatform/DataflowTemplates#templates-plugin, which should make the creation of spec files automatic.
