### ISSUE TITLE
AvroToBigtable

### ISSUE THREAD

**Issue by SidharthMohan** [GoogleCloudPlatform/DataflowTemplates#18]
I am tying to import and run this project .. The AVRO to Big Table conversion is missing the BigTableRow.java and BigTableCell.java and hence getting compilation errors on the example

**Comment by chakpongchung** [comment]
same problem here. Also, could you please provide a more detailed tutorial here how I can create the table in big table to cater for the input avro schema?

**Comment by bvolpato** [comment]
Please check the readme.

`mvn protobuf:compile` is required to generate such files.


This issue was stale for some time. Please reopen it if there is a follow up or any related questions.
