### ISSUE TITLE
Kafka to BigQuery with SSL

### ISSUE THREAD

**Issue by matheusjerico** [GoogleCloudPlatform/DataflowTemplates#180]
How I can use kafka to bigquery template (https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/kafka-to-bigquery or https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/dataflow/flex-templates/kafka_to_bigquery) with SSL Kafka?

I didn't find any configuration to pass SSL files (truststore/keystore) to template. 

How I can make this configuration?

**Comment by sabhyankar** [comment]
We are working on release a Kafka template that supports additional security capabilities including SSL and Kerberos. This should be available in this repo later in this quarter.

**Comment by matheusjerico** [comment]
@sabhyankar Thanks!

**Comment by orensham** [comment]
@matheusjerico https://github.com/doitintl/dataflow-kafka-to-bq

**Comment by Ozzyz** [comment]
@sabhyankar any updates on this? 
Has it been implemented?

**Comment by nosovk** [comment]
@dodywicahyo do you managed to solve an issue somehow?

**Comment by jasmas** [comment]
https://cloud.google.com/dataflow/docs/guides/templates/ssl-certificates

**Comment by nosovk** [comment]
> https://cloud.google.com/dataflow/docs/guides/templates/ssl-certificates

as I see - no kafka support

**Comment by jasmas** [comment]
> > https://cloud.google.com/dataflow/docs/guides/templates/ssl-certificates
> 
> as I see - no kafka support

This tells you how to store and use the cert chain with dataflow. Everything else about how to use it is documented in org.apache.kafka.
