### ISSUE TITLE
[Bug]: Google Ads to BigQuery broken due to Ads API sunset 

### ISSUE THREAD

**Issue by bcoryat** [GoogleCloudPlatform/DataflowTemplates#1801]
### Related Template(s)

goog-dataflow-google-ads-to-bigquery

### Template Version

latest

### What happened?

The ADs API version (v14) that the Beam GoogleAds I/O Connector has been sunset. See Beam issue:
https://github.com/apache/beam/issues/32241

The Dataflow template needs updated to use the updated Beam GoogleAds I/O Connector when it becomes available.

**Comment by Abacn** [comment]
upstream fix done and will be available in Beam 2.59.0.

**Comment by bcoryat** [comment]
The template is still referencing v14: 
com.google.ads.googleads.v14.services.GoogleAdsRow;

**Comment by Abacn** [comment]
template has not yet upgraded to Beam 2.59.0 (which is not released yet). Once that done should be fixed

**Comment by tarush-bitstrapped** [comment]
Facing similar issue, when2.59.0  is expected to release ?

**Comment by bcoryat** [comment]
Beam 2.59.0 has been released: https://beam.apache.org/blog/beam-2.59.0/ 

When will the  template be updated?

**Comment by Abacn** [comment]
It's in #1867. Template release weekly and it takes 1-2 week to roll out to production. Until then one can checkout template themself and build the template.

**Comment by Abacn** [comment]
Fixed by #1867.
