### ISSUE TITLE
MergeInfoMapper, DataStreamClient Files missing - Kafka to BQ

### ISSUE THREAD

**Issue by riyaraj8052** [GoogleCloudPlatform/DataflowTemplates#193]
Hi,
The build failed with the files missing.
[ERROR]   symbol:   class MergeInfoMapper
[ERROR]   location: package com.google.cloud.teleport.v2.cdc.mappers

[ERROR]   symbol:   class DataStreamClient
[ERROR]   location: package com.google.cloud.teleport.v2.utils

**Comment by Waltorw** [comment]
I have the same issue. This classes are used in `DataStreamBigQueryMerger`.

**Comment by ilya-kozyrev** [comment]
Hello, 
I have a similar issue, can't build a maven project using common as dependencies.

**Comment by KhaninArtur** [comment]
Also faced this issue. Are there any updates?

**Comment by dennislapchenko** [comment]
Same issue. Any updates?

**Comment by prathapreddy123** [comment]
This is fixed now. Can you please verify and confirm

**Comment by ilya-kozyrev** [comment]
> This is fixed now. Can you please verify and confirm

Thank you, everything works well

**Comment by bvolpato** [comment]
This seems to be solved / verified.

Please reopen it if there is a follow up or any related questions.
