### ISSUE TITLE
Documentation is quite opaque | Requesting to improve

### ISSUE THREAD

**Issue by devopsifi** [GoogleCloudPlatform/DataflowTemplates#196]
Hi Guys,
There's a scope of improvement when it comes to the documentation. Someone who has knowledge of dataflow, pubsub and mysql won't be able to get it done with one shot. Especially, the configuration aspect is quite convoluted. Please, consider my request and make it more simpler.

**Comment by prathapreddy123** [comment]
Can you be more specific on which template are you referring to?

**Comment by maosi-chen** [comment]
1. Please clean/adjust the README structure. May consider adding numbering to the titles and subtitles and Explaining why do they exist and how are they connected to other items. 
2. As devopsception mentioned, please provide complete examples of the configuration files and post them in the repository.
