### ISSUE TITLE
Is this updated with latest Dataflow Templates? from march 2nd?

### ISSUE THREAD

**Issue by ricardolui** [GoogleCloudPlatform/DataflowTemplates#2]
It seems the JavascriptTextTransformer is missing from the source code (probably changed on March 2nd).

**Comment by mikeleonard** [comment]
Came here from the blog post to see how the javascript udf example was implemented. +1 for adding the source code. Thanks.

**Comment by ricardolui** [comment]
Hi, 

I hope they update the latest source code, but you can see examples on the test example folder.
I've tested it and it works.
Basically you will receive the text inline and you can convert to JSON or whatever. Check the examples bellow.

https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/src/test/resources/com/google/cloud/teleport/templates/common/JavascriptTextTransformerTest/GoodScripts

**Comment by ryanmcdowell** [comment]
The repo has been updated with some added documentation in the README for UDF usage.

**Comment by mikeleonard** [comment]
Thanks a lot.
