### ISSUE TITLE
Debezium Connector running -- and connected -- but not publishing to Google PubSub

### ISSUE THREAD

**Issue by shanemeister** [GoogleCloudPlatform/DataflowTemplates#209]
Ran the following command from terminal in v2/cdc-parent:
`sudo mvn exec:java -pl cdc-embedded-connector -Dexec.args="dataflow-cdc.properties" -X -e --log
-file connector.txt &`

Tail connector.txt:
`[DEBUG] Adding project dependency artifact: commons-text to classpath
[DEBUG] Adding project dependency artifact: commons-logging to classpath
[DEBUG] Adding project dependency artifact: commons-beanutils to classpath
[DEBUG] Adding project dependency artifact: commons-collections to classpath
[DEBUG] Adding project dependency artifact: slf4j-api to classpath
[DEBUG] joining on thread Thread[com.google.cloud.dataflow.cdc.connector.App.main(),5,com.google.cloud.dataflow.cdc.connector.App]
Logger Binding: org.slf4j.impl.Log4jLoggerFactory@3ce1e49a
org.slf4j.impl.Log4jLoggerFactory
Jan 11, 2021 5:00:28 PM com.github.shyiko.mysql.binlog.BinaryLogClient connect
INFO: Connected to 34.. . . . `

I have gone to MySQL, performed some inserts, and deletes, but no messages are showing up in subscription.  Any ideas?

Help greatly appreciated!

**Comment by shanemeister** [comment]
Come to find out, you don't even need the Google Template connector as documented here -- it does absolutely nothing. You must have the Debezium server running.

**Comment by chetansharmagithub** [comment]
@shanemeister Please share what value you've used for whitelistedTables in dataflow_cdc.properties files ?
Most of the people including me are/were facing issue with instance name. If you're stuck at the same stage, please use your database name as the instance name.
I've got it working by using my database name as the instance name. For example, if my database name is **rdw** and table name is **people**, then my whitelistedTables string for this table will be **rdw.rdw.people**
I hope this helps everyone here.

**Comment by onurtokat** [comment]
Hello,

I would like to move CDC data for each topic. Therefore, I am not using singleTopicMode=true property. It is connected, but there is no change on the topic. When I use database-name as instance-name for table definition on whitelist, it gives below error

`21/07/22 23:48:51 ERROR mysql.MySqlJdbcContext: Unexpected error shutting down the database connection
java.sql.SQLException: Streaming result set com.mysql.cj.protocol.a.result.ResultsetRowsStreaming@2d60d9e6 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.`

What is this? There is no streaming on that backup MySQL instance.
