### ISSUE TITLE
Error deploying cdc in GKE or using docker

### ISSUE THREAD

**Issue by karunakarv** [GoogleCloudPlatform/DataflowTemplates#211]
I have followed the documentation and deployed to GKE and directly using docker run. Bothways, getting the same error. 
Logger Binding: org.slf4j.impl.Log4jLoggerFactory@59fa1d9b
org.slf4j.impl.Log4jLoggerFactory
**Exception in thread "main" java.lang.NumberFormatException: For input string: "${DB_PORT}"**
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:569)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.google.cloud.dataflow.cdc.connector.App.startSender(App.java:218)
        at com.google.cloud.dataflow.cdc.connector.App.main(App.java:131)
Also, requesting to change the docker push command image name. I see while creating it is "cdc-embedded-connector" but pushing it is "dataflow-cdc-connector"

Please suggest if am missing any steps.

**Comment by saifabid** [comment]
For the properties file, pass the full path not the relative path. Thats what fixed it for me

**Comment by chetansharmagithub** [comment]
@karunakarv You're supposed to use actual database port no. here instead of **${DB_PORT}** , which is 3306 for MySQL. 
Also make sure you provide all the required details in **dataflow_cdc.properties** file

**Comment by karunakarv** [comment]
@saifabid @chetansharmagithub  this issue is fixed.
