### ISSUE TITLE
Feature Request: pubsub proto to bigquery job template

### ISSUE THREAD

**Issue by daisy1754** [GoogleCloudPlatform/DataflowTemplates#215]
Currently GCP provides a template for pubsub JSON to bigquery, or pubsub avro to bigquery 
https://cloud.google.com/dataflow/docs/guides/templates/provided-streaming#cloudpubsubsubscriptiontobigquery

It would be great if gcp can also provide template for pubsub protobuf to bigquery since protobuf is also very common (and supported natively via beam). 

FWIW beam-sdks-java-extensions-protobuf provides some similar functionality (although I never got it to work - https://stackoverflow.com/questions/64903586/converting-protobuf-to-bigquery-in-java/65116923#65116923)

**Comment by bvolpato** [comment]
Requested template was created: https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/pubsub-binary-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/PubsubProtoToBigQuery.java

--

This issue has been stale for some time now. Please reopen it if there is a follow up or any related questions.
