### ISSUE TITLE
Not Loading Messages - Kafka

### ISSUE THREAD

**Issue by JoshBello** [GoogleCloudPlatform/DataflowTemplates#217]
Messages are received when using the 'Kafka to Bigquery' template but not when using this:

```
from apache_beam.io.kafka import ReadFromKafka

words = p | "Kafka read" >> ReadFromKafka(consumer_config={"bootstrap.servers": kafka_server}
                                                           ,topics=['topic'])
```

Any ideas?

**Comment by bvolpato** [comment]
This doesn't seem like a Templates topic. If the problem persists, please report an issue with Apache Beam: https://github.com/apache/beam/issues.
