### ISSUE TITLE
PubSubSubscription to BigQuery template omits PubSub attributes in resulting BigQuery table

### ISSUE THREAD

**Issue by LaurensVijnck** [GoogleCloudPlatform/DataflowTemplates#219]
The PubSubSubscription to BigQuery template does not store the PubSub attributes in the resulting BigQuery table. I identified the issue in the V2 code, but somehow the setup for this project is rather peculiar, i.e., only the test setup for V1 seems to be working. If I could get some pointers how to get this working, I'll add a pull request to patch the issue.

Kind regards,

Laurens

**Comment by prathapreddy123** [comment]
Are you referring [pubsub-binary-to-bigquery](https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/pubsub-binary-to-bigquery) template?
