### ISSUE TITLE
No documentation on parameters for certain templates

### ISSUE THREAD

**Issue by ls-youssef-elkhalili** [GoogleCloudPlatform/DataflowTemplates#220]
Hello, 

I am trying to run the `BigQueryToDatstore` template and I'm struggling to find the parameters needed for the pipeline to run. 
The README points to this link https://cloud.google.com/dataflow/docs/templates/provided-templates to check what parameters are needed but that page does not have `Big Query To Datastore` as a listed template.

I am trying to read the code in the template to figure out what parameters are needed but I thought I would raise an issue. 
I apologize in advance if they are somewhere obvious that I missed.

**Comment by prathapreddy123** [comment]
Templates will not be included in [Official docs ](https://cloud.google.com/dataflow/docs/templates/provided-templates) until available on Google Cloud console. BigQueryToDatstore template uses following options:

1.https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/186a757cfabd5e4b109632a8fd2dee5ade418c7b/src/main/java/com/google/cloud/teleport/templates/common/BigQueryConverters.java#L85

2.https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/186a757cfabd5e4b109632a8fd2dee5ade418c7b/src/main/java/com/google/cloud/teleport/templates/common/DatastoreConverters.java#L75

3.https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/186a757cfabd5e4b109632a8fd2dee5ade418c7b/src/main/java/com/google/cloud/teleport/templates/common/ErrorConverters.java#L82

**Comment by ls-youssef-elkhalili** [comment]
Thank you I was able to run the job with these options

```
  readQuery
  readIdColumn
  datastoreWriteProjectId
  datastoreWriteEntityKind
  datastoreWriteNamespace
  errorWritePath
```
