### ISSUE TITLE
Is it possible to export Cloud Spanner to AVRO, with only roles/storage.objectCreator?

### ISSUE THREAD

**Issue by dseomn** [GoogleCloudPlatform/DataflowTemplates#229]
Hi,

I'm trying to use the `Cloud_Spanner_to_GCS_Avro` template to back up our Cloud Spanner databases. I don't want to give the backup creator permission to read old backups, or modify/delete any objects, if possible, so I'm trying to use one bucket for `outputDir` and a second bucket for `tempLocation`. The dataflow worker has `roles/storage.objectCreator` on the output bucket and `roles/storage.objectAdmin` on the temp bucket, but I'm getting an error about missing the `storage.objects.get` permission when trying to access an object named like `<outputDir>/.temp-beam-<something-that-looks-like-a-uuid>/<something-that-looks-like-a-different-uuid>`. Is there any way to get the Dataflow job to write all its temp files to `tempLocation`, so that it only needs `roles/storage.objectCreator` on `outputDir`?

**Comment by prathapreddy123** [comment]
Can you try passing --gcpTempLocation=gs://<temp-buccket> 

https://beam.apache.org/releases/javadoc/2.25.0/org/apache/beam/sdk/extensions/gcp/options/GcpOptions.html#getGcpTempLocation--

**Comment by dseomn** [comment]
I tried passing `gcpTempLocation` in the parameters and in the environment, but both places caused errors about it being unrecognized. Also, the pipeline options section on the Cloud Dataflow dashboard already shows `gcpTempLocation` with the same value as `tempLocation`. Is there some other way to pass in `gcpTempLocation`?

**Comment by prathapreddy123** [comment]
Can you share the command you are using to invoke the template?

**Comment by dseomn** [comment]
We're using the discovery API in Python:

```python
dataflow.projects().templates().launch(
    projectId=...,
    gcsPath=...,
    body={
        'jobName': ...,
        'parameters': {
            'spannerProjectId': ...,
            'instanceId': ...,
            'databaseId': ...,
            'outputDir': ...,
        },
        'environment': {
            'tempLocation': ...,
        },
    },
)
```

And adding `gcpTempLocation` didn't work in either `parameters` or `environment`.

**Comment by prathapreddy123** [comment]
You are correct. If you set tempLocation then the same value will be used for gcpTempLoaction as well.  But the current pipeline is using output dir as templocation (https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/src/main/java/com/google/cloud/teleport/spanner/ExportTransform.java#L393) instead of path provided by templocation option .  I understand that you don't want to provide ability to view existing objects for backup creator but just to isolate problem can you add roles/storage.objectViewer (https://cloud.google.com/storage/docs/access-control/iam-roles) to dataflow worker account and verify if it works.

**Comment by dseomn** [comment]
With just roles/storage.objectCreator and roles/storage.objectViewer, I'm getting `java.io.IOException: Error trying to rewrite gs://<outputDir>/.temp-beam-.../... to gs://<outputDir>/<instanceId>-<databaseId>-2021-03-23_16_15_27-<someInteger>/empty-cloud-spanner-export.avro-00000-of-00001` because of missing the storage.objects.delete permission.

With roles/storage.objectAdmin, it looks like everything worked.

How easy/feasible do you think it would be to change the pipeline to pass in the tempLocation instead of outputDir? Do you think that would solve this?

**Comment by prathapreddy123** [comment]
Yes that will solve but cannot guarantee on the timelines to incorporate the change
