### ISSUE TITLE
Use same group.id in consumer properties

### ISSUE THREAD

**Issue by jocke-ek** [GoogleCloudPlatform/DataflowTemplates#23]
Setting the group.id in the .updateConsumerProperties() still makes the reader to start reading at offset 0 for all jobs.

The setup
```
        Map<String, Object> props = new HashMap<>();
        props.put("group.id", "dataflow-reader");
        props.put("auto.offset.reset", "earliest");

        PCollection<KafkaRecord<String, String>> pcol = p.apply(KafkaIO.<String, String>read()
            .withBootstrapServers(options.getBootstrapServers())
            .withTopics(topics)
            .withKeyDeserializer(StringDeserializer.class)
            .withValueDeserializer(StringDeserializer.class)
            .withNumSplits(1)
            .updateConsumerProperties(props));

```
when I start a new job this is logged in the console.

> Reader-0: reading from name-of-topic-0 starting at offset 0
> ConsumerConfig values: 
> 	auto.commit.interval.ms = 5000
> 	auto.offset.reset = earliest
> 	bootstrap.servers = [xxxx]
> 	check.crcs = true
> 	client.id = 
> 	connections.max.idle.ms = 540000
> 	enable.auto.commit = false
> 	exclude.internal.topics = true
> 	fetch.max.bytes = 52428800
> 	fetch.max.wait.ms = 500
> 	fetch.min.bytes = 1
> 	group.id = Reader-0_offset_consumer_778069295_dataflow-reader

And it looks like that happens here
https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/47881043c80aee3efd59fc728226e559a499a82a/src/main/java/com/google/cloud/teleport/kafka/connector/KafkaUnboundedReader.java#L146

Is it possible to make the reader not start from offset 0 for each new dataflow job instance?

**Comment by yiyijin** [comment]
any updates on this? also just wonder why the group.id needs to be formatted in such a way instead of using the one passed directly by the user?

Also, if this is the case, 2 application instances will always processed the same message, how sould we solve this problem?

**Comment by yiyijin** [comment]
@jocke-ek have you re-solved your issue? if so, can you please share the solution? Thanks!

**Comment by jocke-ek** [comment]
> @jocke-ek have you re-solved your issue? if so, can you please share the solution? Thanks!

No, I did not. Guess the code needs to be patched. I implemented a solution using the kafka connector component (confluentinc/cp-kafka-connect), https://github.com/confluentinc/cp-docker-images

**Comment by azurezyq** [comment]
It seems that this may need an update to KafkaIO to make it accept ValueProviders as configs.

We are working on removing some limitations on the template feature, which will make it easier to implement.

Mark it as "blocked" and will revisit very soon after that feature is ready.

**Comment by bvolpato** [comment]
Flex Templates (v2) were created to avoid having to update KafkaIO to accept ValueProviders.

There has been a set of Kafka templates released as flex, so please try one of them.


This issue has been stale for some time now. Please reopen it if there is a follow up or any related questions.
