### ISSUE TITLE
Allow configuration of write disposition for jdbc to bigquery

### ISSUE THREAD

**Issue by mdhedley** [GoogleCloudPlatform/DataflowTemplates#24]
Currently the jdbctobigquery template sets the bigquery write disposition to append. It would be helpful if a parameter was supported that allowed you to set it to overwrite, in addition to append.

**Comment by azurezyq** [comment]
This seems definitely something we can do.

**Comment by bvolpato** [comment]
It is now supported on the [JdbcToBigQuery (Flex)](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java).

--

This issue has been stale for some time now. Please reopen it if there is a follow up or any related questions.
