### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot find field primaryKey in schema Fields  (cdc parent)

### ISSUE THREAD

**Issue by DavidTanjaya** [GoogleCloudPlatform/DataflowTemplates#251]
anybody know why ? . i ran the dataflow pipeline on cdc-parent file.

![bug](https://user-images.githubusercontent.com/60963516/117621780-27762200-b19c-11eb-81cc-6f3a0785d9d4.JPG)

**Comment by chinmay1994** [comment]
@DavidTanjaya : You can't sync tables that don't have a primary key.

**Comment by DavidTanjaya** [comment]
> @DavidTanjaya : You can't sync tables that don't have a primary key.

sorry, but i've been set the primary key on database that i used. but it still doesn't work
