### ISSUE TITLE
ClassCastException importing integer array from BigQuery Avro export

### ISSUE THREAD

**Issue by O1O1O1O** [GoogleCloudPlatform/DataflowTemplates#26]
When importing an Avro dump of a BigQuery table with repeated integer column (array of integers) we see a class cast exception: 
```
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
    at com.google.cloud.teleport.spanner.AvroRecordConverter.lambda$readInt64Array$11(AvroRecordConverter.java:359)
```

This looks like a line number from the previous commit of this code: 42ce71ea3d1d9c0d0c71a654525f528cbed91939 

I have experienced a similar problem when trying to write the output of BigQuery with a nullable INTEGER column into a Spanner INT64 and I had to do use a function like: 
```
  private Long longVal(Object v, Long defaultValue) {
        return v == null ? defaultValue : Long.parseLong(v.toString());
    }
```

So I think the fix is probably replace
``` 
value.stream().map(x -> x == null ? null : (long) x).collect(Collectors.toList()));
```
with
```
value.stream().map(x -> x == null ? null : Long.parseLong(x.toString)).collect(Collectors.toList()));
```

I have not had a chance to try this fix or develop a test + PR but thought I would share the bug report in case other people are Googling for the answer to those pesky exceptions like I was.

**Comment by biswanag** [comment]
Thanks for noting this issue. We are currently looking at this issue. Will try to get a fix out.

**Comment by O1O1O1O** [comment]
Great, thanks for the fast acknowledgement.  I was able to build a patched version of the code and test, can confirm this patch worked for us:
```
diff --git a/src/main/java/com/google/cloud/teleport/spanner/AvroRecordConverter.java b/src/main/java/com/google/cloud/teleport/spanner/AvroRecordConverter.java
index 1c4298b..13e0536 100644
--- a/src/main/java/com/google/cloud/teleport/spanner/AvroRecordConverter.java
+++ b/src/main/java/com/google/cloud/teleport/spanner/AvroRecordConverter.java
@@ -346,7 +346,7 @@ public class AvroRecordConverter implements SerializableFunction<GenericRecord,
             return Optional.empty();
           }
           return Optional.of(
-              value.stream().map(x -> x == null ? null : (long) x).collect(Collectors.toList()));
+              value.stream().map(x -> x == null ? null : Long.parseLong(x.toString())).collect(Collectors.toList()));
         }
       case STRING:
         {
-- 
2.16.1
```

**Comment by biswanag** [comment]
Can reproduce the problem internally in a test. Will work on the patch.

Similar problems may exist in the other type conversions as well.

**Comment by biswanag** [comment]
I have a fix in progress. This avoids converting to String. Should be available in the next release.

**Comment by biswanag** [comment]
You can see the fix at: https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/0aa0189d5fefce4302f4e2976c06b21bc14c8707/src/main/java/com/google/cloud/teleport/spanner/AvroRecordConverter.java#L353

There is an associated test as well: AvroRecordConverterTest.java 

The compiled template with the fix should be released this week. I will also be going through the other other array type conversions and make sure they work as well.
