### ISSUE TITLE
Support Pub/Sub subscription to GCS

### ISSUE THREAD

**Issue by yu-iskw** [GoogleCloudPlatform/DataflowTemplates#261]
## Motivation
`Cloud_PubSub_to_Avro` and `Cloud_PubSub_to_GCS_Text` support an only input topic. So, if we relaunch a streaming application with the templates, pub/sub messages are discontinuous and are lost while a new subscription is created.

Let's consider if we use the template to back up Pub/Sub messages to GCS. The situation is not good because it is difficult to completely store coming pub/sub messages to GCS. However, if we support Pub/Sub subscription to GCS, we can avoid the situation.

- https://cloud.google.com/dataflow/docs/guides/templates/provided-streaming#pubsub-to-avro-files-on-cloud-storage
- https://cloud.google.com/dataflow/docs/guides/templates/provided-streaming#pubsub-to-text-files-on-cloud-storage

**Comment by yu-iskw** [comment]
I understood it supports, but is not documented well. I will try it out.

https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/src/main/java/com/google/cloud/teleport/templates/PubsubToText.java#L116-L122

**Comment by yu-iskw** [comment]
@n-oden Do you know when the implement is released? 
https://github.com/GoogleCloudPlatform/DataflowTemplates/commit/e99ed74f10ceff6be039b3b5db59ce1ca2fe2a51

The latest and `2021-05-17-00_RC00` seems not to contain the implementation yet.
- https://console.cloud.google.com/storage/browser/dataflow-templates?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false

**Comment by altonotch** [comment]
Would be really nice to have this option. 
If someone can explain how to modify the template code to allow to provide `inputSubscription`, that would be great as well 🤞🏽

**Comment by bvolpato** [comment]
@altonotch The problem is that classic templates do not support runtime configured graph.

So we have to generate one template using `useSubscription` true and one false.

The easiest way seems to be following the steps here https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v1/README_Cloud_PubSub_to_Avro.md, remove the `skipOptions = "inputSubscription"` line and the conditional for `if (options.getUseSubscription()) {`.
