### ISSUE TITLE
Streaming Data Generator - Issues with Timestamps in BQ 

### ISSUE THREAD

**Issue by rfcuinas** [GoogleCloudPlatform/DataflowTemplates#269]
I'm trying to generate timestamp data and insert into BQ with the Streaming Data Generator template and I'm getting insertion errors: 

 ```
{"errors":[{"debugInfo":"","location":"eventtimestamp","message":"Timestamp field value is out of range: 1625786389636999936","reason":"invalid"}],"index":0} 
```
It seems like the timestamp BQ receives is not millis (it has 6 extra digits)

This is the JSON schema I'm using, following the docs:

```
{
  "eventId": "{{uuid()}}",
  "eventTimestamp": {{timestamp()}},
  "signal1": {{integer(100, 10000)}},
  "signal2": {{float(0, 3)}},
  "signal3": {{float(-10, 26)}}
}
```

The BQ field in question ins a TIMESTAMP field.
I've also been able to reproduce this issue by getting the template to generate Avro messages to PubSub and then use another template from Avro Pub/Sub to BQ, same error.

**Comment by ryanmcdowell** [comment]
We may need to update the docs. You should be able to specify the timestamp use `{{date(DATE_FORMAT_HERE)}}` 

Example:
```
{
  "eventTimestamp": "{{ date(\"yyyy-MM-dd HH:mm:ssZ\") }}" 
}
```

Let me know if this works for you.
