### ISSUE TITLE
Location isn't support  in the DLPTextToBigQueryStreaming template

### ISSUE THREAD

**Issue by LuizSDCit** [GoogleCloudPlatform/DataflowTemplates#270]
When you try to pass a `deidentifyTemplateName` parameter ​that have a location like `"projects/${var.project_id}/locations/${var.region}/deidentifyTemplates/${module.de_identification_template.template_id}"` your job report the erro bellow:

```
Error message from worker: com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Not authorized to access requested deidentify template. com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:55) com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72) com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60) com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97) com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68) com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1052) com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398) com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1029) com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871) com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:716)
```

I guess that this error is happened because in the template [we have this line:](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/d4bad3e3e01e19a2bebae97d226794fe0715320d/src/main/java/com/google/cloud/teleport/templates/DLPTextToBigQueryStreaming.java#L559)

```java
this.requestBuilder =
        DeidentifyContentRequest.newBuilder()
            .setParent(ProjectName.of(this.dlpProjectId.get()).toString())
            .setDeidentifyTemplateName(this.deIdentifyTemplateName.get());
```

The line `setParent(ProjectName.of(this.dlpProjectId.get().toString())` it's probably the reason of the templete it's not be able to work with a template that has a location, because according to the [documentation of setParent](https://googleapis.dev/java/google-cloud-dlp/latest/com/google/privacy/dlp/v2/DeidentifyContentRequest.Builder.html#setParent-java.lang.String-) when we pass the parameter like that `"projects/"<var>PROJECT_ID</var>"` it's consider that we are using a global location, as you can see below:

```
public DeidentifyContentRequest.Builder setParent(String value)
 Parent resource name.
 The format of this value varies depending on whether you have [specified a
 processing
 location](https://cloud.google.com/dlp/docs/specifying-location):
 + Projects scope, location specified:<br/>
   `projects/`<var>PROJECT_ID</var>`/locations/`<var>LOCATION_ID</var>
 + Projects scope, no location specified (defaults to global):<br/>
   `projects/`<var>PROJECT_ID</var>
 The following example `parent` string specifies a parent project with the
 identifier `example-project`, and specifies the `europe-west3` location
 for processing data:
     parent=projects/example-project/locations/europe-west3
```

May a possible solution it's be adding a location parameter that have a default value `"global"`, because this solution will give a possibilite to work with location and doesn't will generate a problem to every that use the template with the current behavior, since `"projects/PROJECT_ID"` is equal to `"projects/PROJECT_ID/locations/global"`

**Comment by bharathkkb** [comment]
@prathapreddy123 could you PTAL

**Comment by bvolpato** [comment]
It seems that the Service Account being used for the Dataflow job does not have access to the DLP service / template to proceed with the request.

--

This issue has been stale for some time now. Please reopen it if there is a follow up or any related questions.
