### ISSUE TITLE
Adding filename into bigquery

### ISSUE THREAD

**Issue by tebanramirezm** [GoogleCloudPlatform/DataflowTemplates#273]
I would like an example to add filename from everyfile in a bucket from Google Cloud Storage, that filename add as a column into bigquery

**Comment by jsj14** [comment]
Should the column be autonamed as 'file_name'?

**Comment by bvolpato** [comment]
Can you provide more details? I don't quite get what template you were talking about.

**Comment by bvolpato** [comment]
This issue has been stale for some time now. Please reopen it if there is a follow up or any related questions.
