### ISSUE TITLE
Unable to export spanner databases to Avro in parallel

### ISSUE THREAD

**Issue by yuuis** [GoogleCloudPlatform/DataflowTemplates#278]
Hello,

When multiple databases in the same instance are exported in parallel, the following errors occur:
```
Error message from worker: java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: java.lang.RuntimeException: java.io.FileNotFoundException: gs://xxx-spanner-export/{INSTANCE NAME}-{DB NAME}-2021-07-28_04_36_45-8110926218603720209/{TABLE NAME}.avro-00000-of-00001
```
Actually, if it is not created in GCS.

If I export two in parallel, one will fail with error above, but the other is successful.
And I saw the spanner's metrics, but it was not a high load.

What should I do to solve this error? I can provide further required information.

**Comment by yuuis** [comment]
This error did not occur when exporting to a different GCS bucket for each database.
Is it not supported to export two databases simultaneously to one GCS bucket?

**Comment by iTaybb** [comment]
It seems like a race condition since the temporary folders are probably shared accross different dataflow runs.
I solved it by passing a specific `staging-location` to the dataflow job, and `avroTempDirectory` as a parameter to the template, like so:

```
STAGING_BASE_DIR=gs://$GCS_BUCKET/dataflow-tmp

for DB in $DB_LIST; do
  STAGING_DIR=$STAGING_BASE_DIR/staging/j$RANDOM$RANDOM
  TEMP_DIR=$STAGING_BASE_DIR/avroTemp/j$RANDOM$RANDOM
  echo "Exporting database: $DB"
  gcloud dataflow jobs run export-spanner-$DB-to-gcs-job \
    --project=$PROJECT \
    --gcs-location=$DATAFLOW_TEMPLATE \
    --region=$REGION \
    --parameters="instanceId=$SPANNER_ID,databaseId=$DB,outputDir=$OUTPUT_DIR,avroTempDirectory=$TEMP_DIR" \
    --staging-location=$STAGING_DIR \
    --network=$SUBNETWORK \
    --subnetwork=regions/$REGION/subnetworks/$SUBNETWORK \
    --disable-public-ips
done
```
