### ISSUE TITLE
Readme for DataStreamToBigQuery is a copy of PubSub CDC to BigQuery 

### ISSUE THREAD

**Issue by InigoSJ** [GoogleCloudPlatform/DataflowTemplates#293]
The readme for [DataStreamToBigQuery](https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/datastream-to-bigquery) seems to be (close to) a copy of  [PubSub CDC to BigQuery](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/v2/pubsub-cdc-to-bigquery/README.md).

Could we double check if the steps to recomplile are right? 

Thanks

**Comment by ian-paine-upskill** [comment]
Is this correct? I can't seem to get it working with the documentation.
