### ISSUE TITLE
pubsub to bigquery template: IllegalArgumentException: Table reference is not in [project_id]:[dataset_id].[table_id] format even though it is in that format referencing a valid table

### ISSUE THREAD

**Issue by jonh99** [GoogleCloudPlatform/DataflowTemplates#294]
I am using the pub/sub to bigquery template and after copying and pasting the table path into the template and running the dataflow job, I get the error:

`IllegalArgumentException: Table reference is not in [project_id]:[dataset_id].[table_id] format: stream2bq:tweetdata.Archer`

I don't understand what the issue is with this format. It's properly formatted and a valid table.

**Comment by fin-brown-lp** [comment]
I'm having a potentially similar issue wherein running a custom dataflow fails with logs stating:
```java.lang.IllegalArgumentException: BigQuery dataset not found for table \"project:dataset.table\" . Please create the dataset before pipeline execution. If the dataset is created by an earlier stage of the pipeline, this validation can be disabled using #withoutValidation."```
The table exists so not sure what the issue is. Running in europe-west2.

**Comment by bvolpato** [comment]
BigQuery table refs are `[project_id]:[dataset_id].[table_id]`, but I can't check if your values are valid.

Could you also please post the entire stack trace, if you happen to get it again?


--

This issue has been stale for some time now. Please reopen it if there is a follow up or any related questions.
