### ISSUE TITLE
BigQueryToElasticsearch Not working with Username and password

### ISSUE THREAD

**Issue by Mandark-droid** [GoogleCloudPlatform/DataflowTemplates#303]
Hi All,

Am trying to use the BigQueryToElasticsearch dataflow template. However when I am trying to use it with the Elasticsearch username and password options its not working and giving error that API key param is missing. 

`ERROR: (gcloud.beta.dataflow.flex-template.run) INVALID_ARGUMENT: The template parameters are invalid. Details:
apiKey: Missing required parameter
- '@type': type.googleapis.com/google.dataflow.v1beta3.InvalidTemplateParameters
  parameterViolations:
  - description: Missing required parameter
    parameter: apiKey`

I have checked the code and it seems that it is an option param in the code but while configuring the job using this data flow template its asking for the API key. Please let me know if there is a way around it as we cannot use the API key approach.

[https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/WriteToElasticsearch.java](url)

**Comment by bvolpato** [comment]
It seems that if you specify username and password, they are used in favor of ApiKey:
```
    // If username and password are not blank, use them instead of ApiKey
    if (StringUtils.isNotBlank(options().getElasticsearchUsername())
        && StringUtils.isNotBlank(options().getElasticsearchPassword())) {
      config =
          config
              .withUsername(options().getElasticsearchUsername())
              .withPassword(options().getElasticsearchPassword());
    } else {
      config = config.withApiKey(options().getApiKey());
    }
```

That said, I don't understand why ApiKey is marked as mandatory (will have to figure out).

For now, please add a dummy api key along with username and password to get unblocked.
