### ISSUE TITLE
[pubsub-cdc-to-bigquery] : Error message from worker: org.json.JSONException: JSONObject["status"] not found 

### ISSUE THREAD

**Issue by ee07dazn** [GoogleCloudPlatform/DataflowTemplates#306]
Hello I am trying to use the [pubsub-cdc-to-bigquery](https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/pubsub-cdc-to-bigquery) flex template... it works fine without the transform script, however has given me multiple issues after adding a `schemaFilePath` and `pythonTextTransformFunctionName` along with `pythonTextTransformGcsPath` 

I think most of the issues encountered so far is to do with documentation and minor change in the `image_spec.json` - its missing the definition for `schemaFilePath` but i am more than happy to raise a PR in this regard. 

However, I am not able to move beyond the following point : 

I am getting the following error during run: 

`2021-10-27T16:25:19.569627762ZError message from worker: org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489) org.json.JSONException: JSONObject["status"] not found. org.json.JSONObject.get(JSONObject.java:572) org.json.JSONObject.getString(JSONObject.java:859) com.google.cloud.teleport.v2.transforms.PythonTextTransformer$FailsafePythonUdf$1.finishBundle(PythonTextTransformer.java:489)`

I believe its coming from this line of code : https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/f2a1871d99762ad801589cace7595dda6404a5b6/v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/PythonTextTransformer.java#L489 

Basically, its looking for a key  - `status` in the data. Is this something i need to add to my transform script (see below)...As per the [readme](https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/pubsub-cdc-to-bigquery#readme), I have only changed the transform function as seen below : 

```
import json
import sys

def transform(event):
  """ Return a Dict or List of Dict Objects.  Return None to discard
      Input: JSON string | Python Dictionary
      Output: Python Dictionary | JSON string
  """
  try:
    event['properties']['netlify_ab_flag'] = event['properties'].pop('netlify-ab-flag')
  except KeyError:
    ...
  # event = json.dumps(event)
  return event

# DO NOT EDIT BELOW THIS LINE
# The remaining code is boilerplate required for
# dynamic handling of event batches from the main
# dataflow pipeline. the transform() function should
# be the initial entrypoint for your custom logic.
def _handle_result(result):
  if isinstance(result, list):
    for event in result:
      if event:
        print(json.dumps(event))
  elif result:
    print(json.dumps(result))

if __name__ == '__main__':
  # TODO: How do we handle the case where there are no messages
  file_name = sys.argv[1]
  with open(file_name, "r") as data_file:
    for cnt, raw_data in enumerate(data_file):
      raw_events = "[%s]" % raw_data

      data = json.loads(raw_events)

      if isinstance(data, list):
        for event in data:
          _handle_result(transform(event))
      else:
        event = data
        _handle_result(transform(event))

```

Something that i also tried, was adding `success` key to the event in the above script but that leads to a completely different error. Can someone please suggest what's going on and/or the fix ?

**Comment by dodywicahyo** [comment]
I also have "Template launch failed: exit status 1" while using schemaFilePath parameter. On console logs:
{"container_id":"da9e7b892fe8c66e178d37c83b1af333ec322c215f0c3571ca6c374238f6628e","severity":"INFO","time":"2022/07/15 05:24:38.929585","line":"exec.go:66","message":"\tat com.google.cloud.teleport.v2.cdc.mappers.BigQueryMapper.withDefaultSchemaFromGCS(BigQueryMapper.java:125)"}
{"container_id":"da9e7b892fe8c66e178d37c83b1af333ec322c215f0c3571ca6c374238f6628e","severity":"INFO","time":"2022/07/15 05:24:38.929682","line":"exec.go:66","message":"\tat com.google.cloud.teleport.v2.templates.PubSubCdcToBigQuery.run(PubSubCdcToBigQuery.java:344)"}
{"container_id":"da9e7b892fe8c66e178d37c83b1af333ec322c215f0c3571ca6c374238f6628e","severity":"INFO","time":"2022/07/15 05:24:38.929796","line":"exec.go:66","message":"\tat com.google.cloud.teleport.v2.templates.PubSubCdcToBigQuery.main(PubSubCdcToBigQuery.java:226)"}
{"container_id":"da9e7b892fe8c66e178d37c83b1af333ec322c215f0c3571ca6c374238f6628e","severity":"INFO","time":"2022/07/15 05:24:38.958680","line":"exec.go:52","message":"java failed with exit status 1"}
{"container_id":"da9e7b892fe8c66e178d37c83b1af333ec322c215f0c3571ca6c374238f6628e","severity":"INFO","time":"2022/07/15 05:24:38.958734","line":"launch.go:77","message":"Template launch failed: exit status 1"}
{"container_id":"da9e7b892fe8c66e178d37c83b1af333ec322c215f0c3571ca6c374238f6628e","severity":"INFO","time":"2022/07/15 05:24:38.958754","line"...

and this my json schemaFile:
`[
    {
        "name": "user_id",
        "type": "INTEGER",
        "mode": "REQUIRED"
    },
    {
        "name": "username",
        "type": "STRING"
    },
    {
        "name": "created_at",
        "type": "TIMESTAMP"
    },
    {
        "name": "updated_at",
        "type": "TIMESTAMP"
    },
    {
        "name": "dbz_op",
        "type": "STRING"
    },
    {
        "name": "dbz_timestamp",
        "type": "TIMESTAMP"
    },
    {
        "name": "dbz_lsn",
        "type": "INTEGER"
    },
    {
        "name": "dbz_txId",
        "type": "INTEGER"
    }
]` 

To stage job:
```
gcloud beta dataflow flex-template run ${JOB_NAME} \
--project=${PROJECT}  \
--region=${REGION} \
--template-file-gcs-location=${TEMPLATE_IMAGE_SPEC} \
--service-account-email=${SERVICE_ACCOUNT} \
--parameters inputSubscription=${SUBSCRIPTION} \
--parameters outputDatasetTemplate=${DATASET_TEMPLATE} \
--parameters outputTableNameTemplate=${TABLE_TEMPLATE} \
--parameters outputDeadletterTable=${DEADLETTER_TABLE} \
--parameters javascriptTextTransformGcsPath=${UDF_SCRIPT} \
--parameters javascriptTextTransformFunctionName=transform \
--parameters schemaFilePath=gs://${DATASET_TEMPLATE}/schemas/debezium-test-users.json
```
Even if add schemaFilePath option inside ${TEMPLATE_IMAGE_SPEC}, I still got same error, and then Dataflow job failed.

**Comment by dodywicahyo** [comment]
In BigqueryMapper.java:
```
public BigQueryMapper<InputT, OutputT> withDefaultSchemaFromGCS(String filePath) {
    if (filePath == null) {
      return this;
    }
    // TODO: A supplier that reloads the GCS file regularly would allow
    // a user to change the file w/o tearing down the pipeline.
    String schemaStr = GCSUtils.getGcsFileAsString(filePath);
    List<Field> schemaFields = BigQueryConverters.SchemaUtils.schemaFromString(schemaStr);

    Map<String, StandardSQLTypeName> schema = new HashMap<String, StandardSQLTypeName>();
    for (Field field : schemaFields) {
      schema.put(field.getName(), field.getType().getStandardType());
    }

    this.defaultSchema = schema;
    return this;
  }

```
Error fired from line 125 of this file, which is:
`List<Field> schemaFields = BigQueryConverters.SchemaUtils.schemaFromString(schemaStr);`

Is pubsub-cdc-to-bigquery not provide "schemaFilePath" correctly by it's parameter? Or is there something wrong with my above schema table?

**Comment by dodywicahyo** [comment]
My problem is solved by set "mode" = "NULLABLE" for every field in my table schema.
