### ISSUE TITLE
Failed to read artifact descriptor for com.google.cloud.dataflow.cdc:cdc-common:jar:0.1

### ISSUE THREAD

**Issue by Moolman** [GoogleCloudPlatform/DataflowTemplates#313]
Good day,

The goal is to compile cdc-change-applier but started getting the below issue:

```
mvn exec:java -pl cdc-change-applier -Dexec.args="--runner=DataflowRunner \
              --inputSubscriptions=${PUBSUB_SUBSCRIPTIONS} \
              --updateFrequencySecs=300 \
              --changeLogDataset=${CHANGELOG_BQ_DATASET} \
              --replicaDataset=${REPLICA_BQ_DATASET} \
              --project=${GCP_PROJECT} \
              --useSingleTopic=true"
```

## The steps I followed to get to the problem. 

1. I ran `mvn clean install`  from `/DataflowTemplates/v2/cdc-parent` directory. Build successfull
2. When running the below build in `/DataflowTemplates/v2/cdc-parent` directory, it fails with error stated below statement:

```
mvn exec:java -pl cdc-change-applier -Dexec.args="--runner=DataflowRunner \
              --inputSubscriptions=${PUBSUB_SUBSCRIPTIONS} \
              --updateFrequencySecs=900 \
              --changeLogDataset=raw_change_log_ds_test \
              --replicaDataset=raw_replica_ds_test \
              --project=${GCP_PROJECT_ID} \
              --useSingleTopic=true"

```

## Narrowing the problem down

When running ```mvn clean install``` in DataflowTemplates/v2/cdc-parent/cdc-change-applier I get the following error:

![image](https://user-images.githubusercontent.com/7881187/143689950-19aac6f1-415b-4f4e-aed8-db310cf98af9.png)

I have tried running `mvn clean install` on windows and linux. Both giving the same problem. 

I have followed all these steps up to formatting the code: [https://github.dev/GoogleCloudPlatform/DataflowTemplates/tree/main/v2/cdc-parent](https://github.dev/GoogleCloudPlatform/DataflowTemplates/tree/main/v2/cdc-parent)

**Comment by Moolman** [comment]
Had to reclone and recompile which solved the problem

**Comment by nidzo17** [comment]
hmm, I have the same issue and several recloning didn't help. macOS
