### ISSUE TITLE
TextIOToBigQuery.java why is calling .apply(BigQueryConverters.jsonToTableRow())  as method

### ISSUE THREAD

**Issue by AndresUrregoAngel** [GoogleCloudPlatform/DataflowTemplates#32]
Hello guys ,

My question is very simple , why are you using on the class `TextIOToBigQuery.java` the action:
`.apply(BigQueryConverters.jsonToTableRow())` like a method instead that a new class lie : `.apply(new BigQueryConverters.jsonToTableRow())` because really is a class ?

thanks so much for confirming.

**Comment by azurezyq** [comment]
Sorry that maybe I got confused here. But .apply() accepts a PTransform object while BigQueryConverters.jsonToTableRow() method returns one.

I don't see problems here, could you please clarify?

**Comment by bvolpato** [comment]
`BigQueryConverters.jsonToTableRow()` returns an instance of `PTransform`. It is the same thing as doing `new JsonToTableRow()`. You can pass in any PTransform to `.apply()`
 
--

This issue has been stale for some time now. Please reopen it if there is a follow up or any related questions.
