### ISSUE TITLE
Elasticsearch URL Validation do not allow access behind routes (used with api gateways)

### ISSUE THREAD

**Issue by radurga** [GoogleCloudPlatform/DataflowTemplates#320]
With the present code, host input can be '$host/$route2elasticsearch'
> www.example.com/elasticMicroService

But because of the trailing route, InternetDomainName.isValid return false and then the code fails when decoding in Base64 the host that is neither an encoded cloud id.

https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/e57f23e793a8ba20e626983b208ebda65abaadb8/v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ConnectionInformation.java#L53

For security reasons, no workaround can be found with exposing a specific port or something else on our servers.

This could be resolved by trimming the host before validation.

**Comment by radurga** [comment]
this is linked to issue https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/302

**Comment by radurga** [comment]
I have an arror on project initialization:
```sh
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.2:compile (default-compile) on project google-cloud-teleport-java: Compilation failure
[ERROR] /DataflowTemplates/src/main/java/com/google/cloud/teleport/templates/common/JavascriptTextTransformer.java:[38,33] package jdk.nashorn.api.scripting does not exist
```

**Comment by bvolpato** [comment]
Fixed by https://github.com/GoogleCloudPlatform/DataflowTemplates/commit/b8ff5473e3e16d532042b3941c317efeee22f787
