### ISSUE TITLE
Pub/Sub Proto to BigQuery

### ISSUE THREAD

**Issue by fin-brown-lp** [GoogleCloudPlatform/DataflowTemplates#323]
The new [Pub/Sub Proto to BigQuery template](https://cloud.google.com/dataflow/docs/guides/templates/provided-streaming#pubsub-proto-to-bigquery) is listed in the docs but exists neither here nor on the template dropdown list of options. Is it in the process of being added? 

Any ideas? 

I'd rather not upload as a custom template and have to manually specify all the parameters.

Thanks!

**Comment by zhoufek** [comment]
The code exists under [v2/pubsub-binary-to-bigquery](https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/main/v2/pubsub-binary-to-bigquery).

Showing it in the Cloud Console is pending some translation requests for a sidebar tutorial, similar to what some templates have now. I don't have an ETA on when those will be complete, but I've followed up with the owner on that.

Sorry for the confusion. I'll add an update once I get word on the translation.

**Comment by zhoufek** [comment]
The translations are done. I'm adding the template to our released templates. I'm hoping to get it into next week's release, but it could take longer. I'll add an update once it is part of a rollout.

**Comment by fin-brown-lp** [comment]
Amazing! thanks for the swift action.

**Comment by zhoufek** [comment]
This template has started rolling out. You may or may not see it depending on your chosen region, but I'm seeing it in one of the regions that it is currently available in:

<img width="578" alt="us-east1 pub:sub templates" src="https://user-images.githubusercontent.com/83302349/150378883-d92c1257-f1e4-4bd7-b5f0-6510619e91a6.png">

It'll take a few days, probably until Sunday or Monday, for the rollout to reach all regions. I'll provide an update and close this issue once it is available in all of them.

**Comment by zhoufek** [comment]
This should now be available in all regions.
