### ISSUE TITLE
BigQueryToBigTable template fails when the bigquery values are null

### ISSUE THREAD

**Issue by sreevidyasama** [GoogleCloudPlatform/DataflowTemplates#325]
When executing the flex template in v2 BigQueryToBigTable, the export is successful when all the columns have non null values. But if any of the value in Bigquery is null, the job fails with this error. 

java.lang.NullPointerException com.google.cloud.teleport.v2.transforms.BigQueryConverters$AvroToMutation.apply(BigQueryConverters.java:132)

The avro mutation is not handling null values correctly and fails when it converts the value to string.

**Comment by zhoufek** [comment]
I have a fix for this locally and have opened an internal review to get it approved.

**Comment by zhoufek** [comment]
This was fixed in https://github.com/GoogleCloudPlatform/DataflowTemplates/commit/7066b9d79e6964036b997a1df5c1b436f9a61ad8

Since it's fixed, I'm going to close this issue.
