### ISSUE TITLE
FAILED_PRECONDITION following steps on Pub/Sub Proto to BigQuery guide

### ISSUE THREAD

**Issue by fin-brown-lp** [GoogleCloudPlatform/DataflowTemplates#333]
Hi,

I'm trying to follow the steps on the guide for running a custom Pub/Sub Proto to BigQuery pipeline [here](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/pubsub-binary-to-bigquery/docs/PubSubProtoToBigQuery/README.md). When I run the ```gcloud beta dataflow flex-template run ...``` command I'm getting the following error:
```html
ERROR: (gcloud.beta.dataflow.flex-template.run) FAILED_PRECONDITION: Unable to parse template file 'gs://$BUCKET/pubsub-proto-to-bigquery-image-spec-template.json'.
- '@type': type.googleapis.com/google.rpc.PreconditionFailure
  violations:
  - description: Invalid signed integer 'PUBSUB_TOPIC'.
    subject: 61:34
    type: JSON
  - description: Expected an identifier or an integer.
    subject: 61:34
    type: JSON
```
The only parameter in the image spec template with type PUBSUB_TOPIC is the outputTopic but the topic i'm providing is definitely valid (in format projects/$PROJECT/topics/$TOPIC) and I can see it under ```gcloud pubsub topics list```.

Any ideas?

I'm using
```
Google Cloud SDK 364.0.0
alpha 2021.11.05
app-engine-python 1.9.96
beta 2021.11.05
bq 2.0.71
core 2021.11.05
gsutil 5.4
```

Thanks!

**Comment by fin-brown-lp** [comment]
found a couple of issues in the [image spec JSON](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/pubsub-binary-to-bigquery/docs/PubSubProtoToBigQuery/pubsub-proto-to-bigquery-image-spec-template.json), missing quotations & extra commas

**Comment by zhoufek** [comment]
Thanks for reporting this! I'll put in a fix.

**Comment by zhoufek** [comment]
Sorry for the late reply. This was fixed in https://github.com/GoogleCloudPlatform/DataflowTemplates/commit/462849e5fdc38e4c474a84f3c9cf131252d00994.

Since this is now fixed, I'm going to close the issue.
