### ISSUE TITLE
[Bug]: mvn compile fails because jdk.nashorn.api.scripting does not exist 

### ISSUE THREAD

**Issue by nidzo17** [GoogleCloudPlatform/DataflowTemplates#348]
### Related Template(s)

cdc-parent

### What happened?

mvn clean compile fails probably because nashorn package is deprecated but google-cloud-teleport-java  still uses it.

### Beam Version

Newer than 2.35.0

### Relevant log output

```shell
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.2:compile (default-compile) on project google-cloud-teleport-java: Compilation failure
[ERROR] /DataflowTemplates/src/main/java/com/google/cloud/teleport/templates/common/JavascriptTextTransformer.java:[38,33] package jdk.nashorn.api.scripting does not exist
[ERROR] 
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.2:compile (default-compile) on project google-cloud-teleport-java: Compilation failure /DataflowTemplates/src/main/java/com/google/cloud/teleport/templates/common/JavascriptTextTransformer.java:[38,33] package jdk.nashorn.api.scripting does not exist
```

**Comment by cardosop** [comment]
do have the same problem...

**Comment by arvinsingla** [comment]
+1 also experiencing this on a fresh pull of main running `mvn clean compile`

**Comment by ekirkland** [comment]
I am trying to test out the cdc-parent template and this error is holding me back.  Is this going to be addressed or am I building incorrectly?

**Comment by pranavbhandari24** [comment]
Which java version are you using?

mvn -version should show which JVM maven uses (it may be not the one used when you simply type java)

**Comment by pranavbhandari24** [comment]
Nashorn was removed in JDK 15, so my guess is that you are using JDK 15 or above. It should work if you downgrade to using JDK 8/11.

**Comment by bvolpato** [comment]
Pranav is correct. However, we have improved the repository by importing Nashorn Standalone, so it is not dependent on the JDK anymore.

--

This issue has been stale for some time now. Please reopen it if there is a follow up or any related questions.
