### ISSUE TITLE
[Bug]: Template missing from gc bucket

### ISSUE THREAD

**Issue by COWI-MI** [GoogleCloudPlatform/DataflowTemplates#361]
### Related Template(s)

PubsubToJdbc.java

### What happened?

This offical dataflow guide [running-the-pubsub-to-java-database-connectivity-jdbc-template](https://cloud.google.com/dataflow/docs/guides/templates/provided-streaming#running-the-pubsub-to-java-database-connectivity-jdbc-template) decribes that the template `PubSub_to_Jdbc` should exists in the buckets:

https://console.cloud.google.com/storage/browser/dataflow-templates/latest
https://console.cloud.google.com/storage/browser/dataflow-templates

But it seems to be missing.

### Beam Version

2.35.0

**Comment by pranavbhandari24** [comment]
It exists inside the `flex` directory under dataflow-templates/latest. Here is the link to the directory https://console.cloud.google.com/storage/browser/dataflow-templates/latest/flex
