### ISSUE TITLE
PubSub to BigQuery partitioned table

### ISSUE THREAD

**Issue by NeoCN** [GoogleCloudPlatform/DataflowTemplates#37]
Is there any plan to add `PubSub to BigQuery partitioned table` template?

**Comment by azurezyq** [comment]
Aare you talking about BigQueryIO.withTimePartitioning?
Yes, we can support that and will provide more updates when we begin working on it.

**Comment by damienhollis** [comment]
@azurezyq any progress on this?

We are using https://cloud.google.com/dataflow/docs/guides/templates/provided-streaming#datastream-to-bigquery and we'd like to partition and cluster the tables but we don't want to have to manually create the tables if we can avoid it.

**Comment by azurezyq** [comment]
I'm no longer working on Dataflow. Sorry.
