### ISSUE TITLE
[Bug]: Dateformats for JDBC Converters seem wrong

### ISSUE THREAD

**Issue by vitoravancini** [GoogleCloudPlatform/DataflowTemplates#374]
### Related Template(s)

JDBCto*

### What happened?

Java docs states that minor case 'h' is for am/pm dates:
![image](https://user-images.githubusercontent.com/4209575/162823942-39f9f65c-c64c-4cf9-9cec-f8bb853fe4da.png)

the JdbcConverter uses date format as such: 

```
DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm:ss.SSSSSS");        
```

Default jdbc connections brings date columns in 0-23 hour format

a date like 2021-01-02 00:41:59 becomes 2021-01-02 12:41:59
and 
a date like 2021-12-30 14:51:10 becomes 2021-12-30 02:51:10

with no ampm signalization.

### Beam Version

2.32.0

**Comment by bvolpato** [comment]
Thanks for bringing this up. This issue was solved by https://github.com/GoogleCloudPlatform/DataflowTemplates/commit/a12beccc3311d0d8d94c5dbd0ae0404deb4dff1d
