### ISSUE TITLE
[Bug]: Unable to run template on Dataflow Runner v2

### ISSUE THREAD

**Issue by mkuthan** [GoogleCloudPlatform/DataflowTemplates#382]
### Related Template(s)

PubSub_Subscription_to_BigQuery

### What happened?

When I run the template:

```
gcloud dataflow jobs run PubsubToBigQuery (...) 
--additional-experiments=use_runner_v2
```

The following error is reported:

```
ERROR: (gcloud.dataflow.jobs.run) INVALID_ARGUMENT: Dataflow Runner v2 requires a valid FnApi job, Please resubmit your job with a valid configuration. Note that if using Templates, you may need to regenerate your template with the '--use_runner_v2'.
```

Ok, let's generate the template using the proposed option:

```
mvn compile exec:java \
-Dexec.mainClass=com.google.cloud.teleport.templates.PubSubToBigQuery \
-Dexec.cleanupDaemonThreads=false \
-Dexec.args=" \
--project=... \
--stagingLocation=... \
--tempLocation=... \
--templateLocation=... \
--runner=DataflowRunner \
--useSubscription=true \
--use_runner_v2
```

Next error, the template is not aware of DataflowPipelineOptions:

```
java.lang.IllegalArgumentException: Class interface com.google.cloud.teleport.templates.PubSubToBigQuery$Options missing a property named 'use_runner_v2'
```

Modify PubSubToBigQuery$Options to inherit from DataflowPipelineOptions instead of PipelineOptions:

```
java.lang.IllegalArgumentException: Class interface com.google.cloud.teleport.templates.PubSubToBigQuery$Options missing a property named 'use_runner_v2'.
```

Clear, DataflowPipelineOptions does not define property like "use_runner_v2". 

Let's try to force using use_runner_v2 using existing experiments option (why the region needs to be a mandatory option for template generation???):

```
mvn compile exec:java \
-Dexec.mainClass=com.google.cloud.teleport.templates.PubSubToBigQuery \
-Dexec.cleanupDaemonThreads=false \
-Dexec.args=" \
(...)
--experiments=use_runner_v2 \
--region=europe-west1"
```
 
Success, the customized template has been deployed on GCS :)

Let's try to deploy the customized template again using Dataflow Runner V2:

```
gcloud beta dataflow jobs run PubsubToBigQuery \
    --gcs-location ... \
    --region ... \
    --staging-location ... \
    --project=... \
    --worker-machine-type=... \
    --enable-streaming-engine \
    --additional-experiments=use_runner_v2 \
    --parameters \
inputSubscription=...,\
outputTableSpec=...,\
outputDeadletterTable=...
```

Success, the job has been deployed and runs on Runner V2!

```
createTime: '2022-05-06T13:13:43.228273Z'
currentStateTime: '1970-01-01T00:00:00Z'
id: 2022-05-06_06_13_41-2523446751447236545
location: ...
name: PubsubToBigQuery
projectId: ...
startTime: '2022-05-06T13:13:43.228273Z'
type: JOB_TYPE_STREAMING
```

As you can see there is a very long journey to run the template on Dataflow Runner V2. 
Is there an easier way to do that?

### Beam Version

Newer than 2.35.0

**Comment by pranavbhandari24** [comment]
Flex templates can be run on runner v2 by default by adding the parameter `experiments` as `use_runner_v2`.

However, Classic templates do not work on runner v2 by default, and need to be build with the same parameter (--experiments=use_runner_v2). Due to this, there is no way for users to run the classic template on runner v2 as is.

I am not sure if the FnApi is backwards compatible, we may have to enable it when we release classic templates if it is.

**Comment by bvolpato** [comment]
+1 to Pranav, please use `experiments`.

--

This issue has been stale for some time now. Please reopen it if there is a follow up or related questions.

**Comment by ashdam** [comment]
gcloud dataflow flex-template run dataflow-template-test \
	--template-file-gcs-location gs://dataflow-templates-europe-west1/latest/flex/PubSub_to_BigQuery_Flex \
	--region europe-west1 \
	--num-workers 1 \
	--enable-streaming-engine \
	--additional-experiments streaming_mode_exactly_once \
	**--experiments=use_runner_v2**
	--additional-user-labels "" \
	--parameters outputTableSpec=XXXXXXX

Still doesnt work :( is there any updated version of this template?
