### ISSUE TITLE
[Bug]: "kafka-to-bigquery" template no longer building

### ISSUE THREAD

**Issue by vicvi1997** [GoogleCloudPlatform/DataflowTemplates#389]
### Related Template(s)

kafka-to-bigquery

### What happened?

I'm trying to build the container image following the process [1] as usual, but during the process I'm getting the error provided in the "Relevant log output" section. The machine I'm using to build the image is a Compute Engine instance running the Debian 9 official image with the additional packages [2] installed. The same process is working fine in past commit [3], on the other hand, the present commit at the time of this writing [4] does not seem to work.

Just to clarify, I'm running the `mvn clean package` command from the directory "./DataflowTemplates/v2", as I usually do.
___
[1]
https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/main/v2/kafka-to-bigquery#building-template
[2]
openjdk-8-jdk
wget
git
mvn
[3]
https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/9916209f4548bae3c56a1476895d6735ebb6c17a
[4]
https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/e70192fa0dda7321533e2c95bf9ac51b4473c634

### Beam Version

Newer than 2.35.0

### Relevant log output

```shell
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for dynamic-templates 1.0-SNAPSHOT:
[INFO] 
[INFO] dynamic-templates .................................. FAILURE [06:32 min]
[INFO] common ............................................. SKIPPED
[INFO] kafka-common ....................................... SKIPPED
[INFO] kafka-to-bigquery .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:34 min
[INFO] Finished at: 2022-05-20T06:53:10Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project dynamic-templates: Could not resolve dependencies for project com.google.cloud.teleport.v2:dynamic-templates:pom:1.0-SNAPSHOT: Could not find artifact com.google.cloud.teleport:integration-testing-lib:jar:1.0-SNAPSHOT in confluent (https://packages.confluent.io/maven/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by bvolpato** [comment]
It is required to have the module `it` installed (you could do `mvn clean install` on `it`).

However, the usual way is to run all required projects together is to use `mvn clean package -f unified-templates.xml`.
