### ISSUE TITLE
[Bug]: Number of runners not scaling down

### ISSUE THREAD

**Issue by vicvi1997** [GoogleCloudPlatform/DataflowTemplates#390]
### Related Template(s)

"kafka-to-bigquery"

### What happened?

I'm executing the "kafka-to-bigquery" template [1] with the Pipeline options [2]. I'm ingesting just 2 messages from the Kafka topic, for simplicity. What I observe, is that the number of workers goes up from 0 to 1 [3] to process the 2 messages (as expected), but then it does not scale down to 0. I keeped the Job running for nearly an hour and the number of workers remained 1. I'm expecting the number of workers to go down to 0 briefly after processing all the messages from the Kafka topic.
___
[1]
https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/9916209f4548bae3c56a1476895d6735ebb6c17a/v2/kafka-to-bigquery#executing-template
[2]
numWorkers=0
maxNumWorkers=8
[3]
From Cloud Logging:
Autoscaling: Raised the number of workers to 1 so that the pipeline can catch up with its backlog and keep up with its input rate.

NOTE: I'm providing a past commit [1] as reference, since I'm currently experiencing an issue building the most recent version of the repository (see https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/389 ).

### Beam Version

Newer than 2.35.0

**Comment by bvolpato** [comment]
@vicvi1997 Dataflow jobs do not scale to 0 on Streaming pipelines.

Please check https://cloud.google.com/dataflow/docs/resources/faq#what_is_the_scaling_range_for_streaming_autoscaling_pipelines
