### ISSUE TITLE
Possible to read file name from JS UDF function?

### ISSUE THREAD

**Issue by alan-ma-umg** [GoogleCloudPlatform/DataflowTemplates#4]
@jasonkuster @ryanmcdowell 

Is there anyway to get the filename from Javascript function? Something similar to FileIO's file path matching to return the file name of being loaded.

Thanks.

**Comment by bvolpato** [comment]
I don't think this is possible. The JavaScript function is read as text, not called from the .js.

This issue was stale for some time. Please reopen it if there is a follow up or any related questions.
