### ISSUE TITLE
[Feature Request]: Split up Pub/Sub to Text or convert it to Flex

### ISSUE THREAD

**Issue by damccorm** [GoogleCloudPlatform/DataflowTemplates#418]
### Related Template(s)

Pub/Sub to Text

### What feature(s) are you requesting?

Right now, there are a few issues with the Pub/Sub to Text template.

1) As of now, there's no way to specify useSubscription through the UI or console.
2) Even if there were, there's not a good way to enforce that only one of inputSubscription or inputTopic are specified, which creates validation challenges
3) Right now, specifying inputSubscription causes things to blow up because its not recognized as a parameter (because its hidden behind useSubscription which is never set to true, see https://github.com/apache/beam/issues/19700)

The best path to fixing this is either (1) split the template into 2, one for each setting of useSubscription or (2) convert it to a flex template.

**Comment by bvolpato** [comment]
@damccorm We now have a flex template for Pub/Sub to Text https://github.com/GoogleCloudPlatform/DataflowTemplates/commit/b9225c19025dcd4a5dd7de66221e86bdfb1ed1bd (by @oleg-semenov)

Can you see if it solves the issue for you?

Also, I am adding some integration tests on https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/448 (validating both from topic and subscription). Let me know if you have any specific scenarios that you'd like to have tested.

**Comment by damccorm** [comment]
This was a customer request so I don't have anything to validate against, but it seems done to me - feel free to close

**Comment by bvolpato** [comment]
Closed by https://github.com/GoogleCloudPlatform/DataflowTemplates/commit/b9225c19025dcd4a5dd7de66221e86bdfb1ed1bd by @oleg-semenov
