### ISSUE TITLE
[Feature Request]: Adding proxy to the configuration

### ISSUE THREAD

**Issue by llermaly** [GoogleCloudPlatform/DataflowTemplates#432]
### Related Template(s)

PubSub to Elasticsearch

### What feature(s) are you requesting?

Adding proxy to the configuration.

We need to create a Dataflow job that ingests from PubSub to Elasticsearch but the job can not make outbound internet connections to reach Elastic Cloud.

Found this article but proxy parameters are part of a maven app, I'm not sure how to use it here.

https://leifengblog.net/blog/run-dataflow-jobs-in-a-shared-vpc-on-gcp/

@Cherepushko could you guide me in a direction to implement it myself ? Thanks

**Comment by llermaly** [comment]
@jeffxf could you share your thoughts on this? We are trying to build the template to add the proxy to the build command without success, seeing this error: 

```
[ERROR] Failed to execute goal on project googlecloud-to-elasticsearch: Could not resolve dependencies for project com.google.cloud.teleport.v2:googlecloud-to-elasticsearch:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: com.google.cloud.teleport.v2:elasticsearch-common:jar:1.0-SNAPSHOT, com.google.cloud.teleport:integration-testing-lib:jar:1.0-SNAPSHOT: Could not find artifact com.google.cloud.teleport.v2:elasticsearch-common:jar:1.0-SNAPSHOT in confluent (https://packages.confluent.io/maven/) -> [Help 1]
```

Is that the way to go?

**Comment by bvolpato** [comment]
@llermaly It is required to have the module `it` installed (you could do `mvn clean install` on `it`) to run builds.

However, the usual way is to run a build with all required modules together, using `mvn clean install -f unified-templates.xml -pl v2/googlecloud-to-elasticsearch` as you can see [here](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/README.md#building).

**Comment by manitgupta** [comment]
I also faced this issue today while trying to build the `Datastream to Spanner` flex template like so:

```
mvn clean package \
-Dimage=${TARGET_GCR_IMAGE} \
-Dbase-container-image=${BASE_CONTAINER_IMAGE} \
-Dbase-container-image.version=${BASE_CONTAINER_IMAGE_VERSION} \
-Dapp-root=${APP_ROOT} \
-Dcommand-spec=${DATAFLOW_JAVA_COMMAND_SPEC} \
-am -pl ${IMAGE_NAME}
```

As described in the README here:
https://github.com/manitgupta/DataflowTemplates/blob/27edd06cf59b5d099da22a83a4bf5661b614868b/v2/datastream-to-spanner/README.md
