### ISSUE TITLE
[Bug]: Incorrect Regex on ElasticSearch templates parameters

### ISSUE THREAD

**Issue by julianlarralde** [GoogleCloudPlatform/DataflowTemplates#441]
### Related Template(s)

BigQueryToElasticSearch, PubSubToElasticSearch, GCSToElasticSearch

### What happened?

Basically, dataflow job fails when including a `0` in the following parameters:

<img width="499" alt="image" src="https://user-images.githubusercontent.com/1661312/185213065-420dc2ff-2fd9-4a14-9ae7-33d581b161e5.png">

Using template:
`gs://dataflow-templates/2022-08-01-00_RC04/flex/BigQuery_to_Elasticsearch`

IDK which beam version the template uses.

### Beam Version

2.35.0

**Comment by bvolpato** [comment]
@julianlarralde Thanks for reporting. We are rolling out a fix for this.

**Comment by julianlarralde** [comment]
Thank you!
