### ISSUE TITLE
[Bug]: Unable to use zeros as part of batch size number

### ISSUE THREAD

**Issue by melpomene** [GoogleCloudPlatform/DataflowTemplates#452]
### Related Template(s)

BigQueryToElasticsearch

### What happened?

Unable to put zeros in my batch size number (like number 5000). Form validation demands size to be valid for regex `^[1-9]+$"`.

<img width="725" alt="Screenshot 2022-08-25 at 21 58 43" src="https://user-images.githubusercontent.com/763476/186757255-74138ccb-3155-4c5b-9a9e-5b5ca73d56fb.png">

Running on Google Dataflow (version 2.39.0)

### Beam Version

Newer than 2.35.0

**Comment by bvolpato** [comment]
Thanks for reporting, @melpomene. This was also reported at https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/441 as well, and we are rolling out a fix, which should be available on all regions within a few days.
