### ISSUE TITLE
[Bug]: Unable to Run Spotless:apply in any module including root directory

### ISSUE THREAD

**Issue by Vasu7052** [GoogleCloudPlatform/DataflowTemplates#460]
### Related Template(s)

pubsub-binary-to-bigquery

### What happened?

I'm trying to run `mvn spotless:apply` and `mvn spotless:check` in the root directory as well as in submodules but I'm receiving this error: 

`Sep 03, 2022 11:22:25 PM com.diffplug.spotless.FormatExceptionPolicyLegacy error
SEVERE: Step 'google-java-format' found problem in 'src/test/java/com/google/cloud/teleport/v2/coders/FailsafeElementCoderTest.java':
com/google/googlejavaformat/java/JavaFormatterOptions has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
java.lang.UnsupportedClassVersionError: com/google/googlejavaformat/java/JavaFormatterOptions has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

Here is my `mvn -v` output:

```
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Java version: 1.8.0_291, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_291.jdk/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

How can I fix this?

### Beam Version

Newer than 2.35.0

**Comment by bvolpato** [comment]
Can you try with Java 11 in your JAVA_HOME? Apparently the format plugin has Java 11 byte-code.

We will likely update the version from 8 to 11 throughout the repository soon.

**Comment by Vasu7052** [comment]
@bvolpato thanks for the quick response. will try Java 11. In the meanwhile do you have any proper documentation that you can share for building the project and running any old or v2 templates?

**Comment by bvolpato** [comment]
> @bvolpato thanks for the quick response. will try Java 11. In the meanwhile do you have any proper documentation that you can share for building the project and running any old or v2 templates?

I think the [README](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/README.md) provides a very good start on building. 

However, my recommendation is to go over this [Flex tutorial](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/tutorials/flex-template.md) - it goes through the entire process of creating, testing, and running a template.

**Comment by Vasu7052** [comment]
> > @bvolpato thanks for the quick response. will try Java 11. In the meanwhile do you have any proper documentation that you can share for building the project and running any old or v2 templates?
> 
> I think the [README](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/README.md) provides a very good start on building.
> 
> However, my recommendation is to go over the [Flex Template Tutorial](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/tutorials/flex-template.md) - it goes through the entire process of creating, testing, and running a template.

Thanks, this is really helpful.
