### ISSUE TITLE
[Bug]: Datastream to BigQuery MERGE not running in correct project

### ISSUE THREAD

**Issue by dixoncrews-gdl** [GoogleCloudPlatform/DataflowTemplates#464]
### Related Template(s)

Datastream to BigQuery

### What happened?

I'm running this template using a different BigQuery project than the Datastream/GCS/Dataflow resources. I'm supplying it as the `--outputProjectId` value and data is flowing into my temporary table, just the MERGE fails:

```
2022-09-09T20:40:23.171ZMerge Job Failed: Exception: com.google.cloud.bigquery.BigQueryException: Access Denied: Project <dataflowproject>: User does not have bigquery.jobs.create permission in project <dataflowproject>.
```

I'm not super familiar with the code, but should this [line](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/4a0664a0d7559ba81353f48dc1cd7e2e928a3fd1/v2/datastream-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToBigQuery.java#L422) use the `options.getOutputProjectId()` value instead of the variable?

### Beam Version

Newer than 2.35.0

**Comment by bvolpato** [comment]
Apparently the variable `bigqueryProjectId` uses `outputProjectId` anyways, when it's present.
Just trying to get more context here: is your `--project` different than `--outputProjectId`? And the error is thrown for the `--project` one?

Couldn't this just be really permission error? I would check if the IAM/Service Account being used has proper permissions on BigQuery.
It saves to BigQuery temporary table through streaming inserts, but the actual merge is done through a job, so the permissions are actually disjoint.

**Comment by dixoncrews-gdl** [comment]
Yes, the `outputProjectId` is set to a different project than `project`. Let's say the Dataflow job is executing on project `projectA` with the output project (BQ) set to `projectB`. 

Data is streaming into the correct temporary table on `projectB`, and the MERGE fails with the error message saying:

```
Merge Job Failed: Exception: com.google.cloud.bigquery.BigQueryException: Access Denied: Project projectA: User does not have bigquery.jobs.create permission in project projectA. Statement: MERGE `projectB.datastream_final.table_name` ...
```

That error message, to me, means it is trying to create a BQ Job in `projectA`, when it should be in the output project, right?

**Comment by bvolpato** [comment]
Got it! Indeed, seems like settings are missing, even though not exactly where you mentioned:

Apparently the issue is here:
https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/common/src/main/java/com/google/cloud/teleport/v2/cdc/merge/BigQueryMerger.java#L174

It seems that the BigQueryOptions builder should receive the `projectId` that was specified in `--outputProjectId`, or it will use the default project configured on Dataflow.
