### ISSUE TITLE
[Feature Request]: Use BigQuery Storage Write API instead of Legacy Streaming API

### ISSUE THREAD

**Issue by dixoncrews-gdl** [GoogleCloudPlatform/DataflowTemplates#466]
### Related Template(s)

Datastream to BigQuery

### What feature(s) are you requesting?

Currently the Datastream to BigQuery template [uses the legacy streaming API](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/datastream-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToBigQuery.java#L404), which is less reliable and more expensive than the [Storage Write API](https://cloud.google.com/bigquery/docs/write-api). 

[It appears Beam 2.36.0 and above supports the Storage Write API](https://beam.apache.org/documentation/io/built-in/google-bigquery/#storage-write-api).

**Comment by bvolpato** [comment]
@oleg-semenov is this change/template planned?

**Comment by bvolpato** [comment]
The Datastream to BigQuery now supports Storage API! Please enable using the parameters from: https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/common/src/main/java/com/google/cloud/teleport/v2/options/BigQueryStorageApiStreamingOptions.java
