### ISSUE TITLE
[Feature Request]: Cloud Storage to Elasticsearch template accept JSON as well as CSV file

### ISSUE THREAD

**Issue by JulPri95** [GoogleCloudPlatform/DataflowTemplates#468]
### Related Template(s)

GCS to Elasticsearch Dataflow Template

### What feature(s) are you requesting?

Currently, the GCS to Elasticsearch Dataflow Template only accepts data in CSV format to be ingested by Elasticsearch. In my use case, we are receiving change files in GCS and processing these into JSON entities to then send over to Firestore using WriteToDatastore and a JSON-to-Entity UDF. I want to be able to take advantage of this process to also send the data to Elasticsearch as the amount of data we are processing overwhelms the Firestore to Elasticsearch Out-of-the-box extension. So my plan would be to trigger a Dataflow batch job to use the same file that is being created for Firestore and send it to Elasticsearch but unfortunately the pertinent template does not allow the use of JSON files. I also can't find a UDF that converts the files to CSV though I suppose I could make one, but it doesn't seem very practical to convert a JSON into a CSV when the first two steps of the GCS to Elasticsearch template are to convert the CSV into a JSON.
Is this something that would be possible to implement? Or is there a particular reason why the template only accepts CSV files?
Thank you!

**Comment by AfvanJaffer** [comment]
Is there any update on this, can we have the support for json format also
