### ISSUE TITLE
Multiple BootstrapServers for KafkaToBigQuery parameters

### ISSUE THREAD

**Issue by bmd-benitaclarissa** [GoogleCloudPlatform/DataflowTemplates#47]
Hi,

I notice there is a parameter called bootstrapServers in https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/src/main/java/com/google/cloud/teleport/templates/KafkaToBigQuery.java. I am trying to using 3 kafka brokers to sync data to BigQuery from Kafka. I cannot use comma "," to separate the brokers parameter. 

Could you tell me how to set the bootstrap servers so the dataflow would ingest from mulitple kafka brokers?

Thanks in advance.

**Comment by bvolpato** [comment]
This was fixed. Commas are now supported. Thanks for reporting.
