### ISSUE TITLE
Nested Fields for JSON to TableSchema

### ISSUE THREAD

**Issue by shsunil11** [GoogleCloudPlatform/DataflowTemplates#51]
In the "GCS Text to BigQuery" template, the JSON to TableSchema Serializable function does not handle nested Fields.

**Comment by danneaves-ee** [comment]
Plus one for this issue, was pretty frustrating finding out the hard way. Maybe good to mention here at least; https://cloud.google.com/dataflow/docs/guides/templates/provided-batch#cloud-storage-text-to-bigquery

**Comment by wtait1-ff** [comment]
Looks like this can be resolved as a duplicate of https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/8?
