### ISSUE TITLE
[Bug]: Unable to set flex template use_public_ips=False for workers

### ISSUE THREAD

**Issue by bahmandar** [GoogleCloudPlatform/DataflowTemplates#512]
### Related Template(s)

Python Flex Template Creation

### What happened?

Running a command like this
```
gcloud dataflow flex-template run <job-name> \
--template-file-gcs-location <template-location> \
--parameters ^~^uris=gs://test-file-location ~use_public_ips=false
```
```
ERROR: (gcloud.dataflow.flex-template.run) INVALID_ARGUMENT: The template parameters are invalid. Details:
use_public_ips: Unrecognized parameter
- '@type': type.googleapis.com/google.dataflow.v1beta3.InvalidTemplateParameters
  parameterViolations:
  - description: Unrecognized parameter
    parameter: use_public_ips
- '@type': type.googleapis.com/google.rpc.DebugInfo
  detail: |-
    [ORIGINAL ERROR] generic::invalid_argument: The template parameters are invalid. Details:
    use_public_ips: Unrecognized parameter [google.rpc.error_details_ext] { message: "The template parameters are invalid. Details: \nuse_public_ips: Unrecognized parameter" details { type_url: "type.googleapis.com/google.dataflow.v1beta3.InvalidTemplateParameters" value: "\n(\n\016use_public_ips\022\026Unrecognized parameter" } } 54820903 { 1 { 1 { 1: "cloud/dataflow/router/services/templates/flex_template_handler.cc" 2: 130 } } }
```

Adding --disable-public-ips outside of parameters will cause both the flex container and the sdk container to not have public ips. This causes install issues because we only want the workers to not have public ips.

I suspect it is related to not being able to explicitly set `use_public_ips=true`

Moved bug from here: https://github.com/apache/beam/issues/22727

### Beam Version

Newer than 2.35.0

**Comment by bvolpato** [comment]
Please use the option `usePublicIps` (camel case) instead.

**Comment by bvolpato** [comment]
It seems that the name is a bit counter-intuitive, but the name for the option seems to be `no_use_public_ips`.

Please see https://cloud.google.com/dataflow/docs/reference/pipeline-options for more details.

**Comment by bahmandar** [comment]
no_use_public_ips won't work. it is looking for a two part argument and justing putting in one side will fail.

**Comment by bvolpato** [comment]
Have you tried `no_use_public_ips=true`?

**Comment by bahmandar** [comment]
let me test that out now.

**Comment by bahmandar** [comment]
The command was tested but it seems like the flex runner also did not use the external public instead of only the sdk workers. Either way this project was completed some time ago so you can close this issue. Thanks!
