### ISSUE TITLE
[Bug]: MongoDB to BigQuery batch template only considers the first document when generating the BQ write schema

### ISSUE THREAD

**Issue by ahmedabu98** [GoogleCloudPlatform/DataflowTemplates#513]
### Related Template(s)

MongoDbToBigQuery

### What happened?

When using this template, the implicit assumption is that all documents in the MongoDB collection have the same schema. The template takes the [first document](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/27d79bea05da051d9c34fcf7449e2d02848ff4ec/v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbUtils.java#L87) in the collection and [extracts a BQ schema](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/27d79bea05da051d9c34fcf7449e2d02848ff4ec/v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbUtils.java#L52-L58) from it. This works well when all documents indeed conform to the same schema, but if there's even one document that has an extra field, the whole load job will fail due to schema mismatch. 

For example, the following collection would work:
doc1, schema {int, string, bool, bool}
doc2, schema {int, string, bool}

But the following will not:
doc1, schema {int, string, bool}
doc2, schema {int, string, bool, bool}

This is because only the first document is looked at. The ideal behavior would be that the generated BQ schema would attempt to account for the schema in all the documents.

### Beam Version

2.35.0

### Relevant log output

```shell
"message" : "Error while reading data, error message: JSON parsing error in row starting at position 226: No such field: <new_field>. File: gs://dataflow-staging-us-central1-
```

**Comment by ahmedabu98** [comment]
@theshanbhag tagging for visibility

**Comment by theshanbhag** [comment]
@ahmedabu98  Yes. Currently the template does not support the UDF and we are considering the first document to create the BigQuery table. It will change eventually with introduction of UDF.

**Comment by ahmedabu98** [comment]
Thanks! Is there a timeline we can follow for this feature? Also, are there any workarounds someone can implement in the meantime?

**Comment by theshanbhag** [comment]
Hi @ahmedabu98  we have included the support for UDF in latest release.

**Comment by ahmedabu98** [comment]
Thanks @bvolpato and @theshanbhag, I'm looking through #523 and I'm not sure if the problem mentioned in this issue is solved yet.  Support for getting TableSchema after invoking a UDF is added, but it still only looks at the first Document to create the schema. ie. the new `getTableFieldSchemaForUDF` calls `getMongoDbDocument` which still only considers and returns the [first Document](https://github.com/theshanbhag/DataflowTemplatesFork/blob/ba1056f6513fd337ffd8b7ef49785de178d7cd75/v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbUtils.java#L111).

Am I missing something?

**Comment by ahmedabu98** [comment]
Hmmm, does UDF support possibly allow for a workaround? Is there a way this can be utilized to rearrange a MongoDB collection such that the Document with the most columns is first?

**Comment by theshanbhag** [comment]
The UDF will help you to define the Javascript functions that will take Document as input and you can modify the document as per your requirement. Even if we consider the first document you can still add fields that are missing in your return document from the UDF.

**Comment by ahmedabu98** [comment]
Is there a plan to support this on the utils side instead? It would makes sense to not burden the user with writing the logic of setting a reliable TableSchema.

**Comment by JoshAubrey** [comment]
Sub'd, thanks for looking into this! Also just ran into it.

**Comment by juddbaguio** [comment]
FF
