### ISSUE TITLE
[Bug]: Running mvn compile in v1 folder throws an error

### ISSUE THREAD

**Issue by eenclona-google** [GoogleCloudPlatform/DataflowTemplates#518]
### Related Template(s)

N/A

### What happened?

I ran "mvn compile" inside the DataflowTemplates/v1/ folder but it throws a build failure (see below).

It couldn't find the artifact - com.google.cloud.teleport.metadata:metadata. 

Can you please advise how to resolve it?

### Beam Version

Newer than 2.35.0

### Relevant log output

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:52 min
[INFO] Finished at: 2022-11-23T16:29:05Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project classic-templates: Could not resolve dependencies for project com.google.cloud.teleport:classic-templates:jar:1.0-SNAPSHOT: Could not find artifact com.google.cloud.teleport.metadata:metadata:jar:1.0-SNAPSHOT in confluent (https://packages.confluent.io/maven/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by bvolpato** [comment]
The module `metadata` is outside the v1 module (project root), so the best way to do it is either:
- Going to `metadata/` and running `mvn install` first
- Or simply running `mvn compile -pl v1 -am` (where `-am` stands for also making dependents).

**Comment by eenclona-google** [comment]
I totally missed that folder! Thank you very much!
