### ISSUE TITLE
[Bug]: Cannot create/load docker images using mvn package for kafka to bigquery

### ISSUE THREAD

**Issue by ApurvaKusum** [GoogleCloudPlatform/DataflowTemplates#546]
### Related Template(s)

v2/kafka-to-bigquery

### What happened?

As per documentation provided, "mvn package" should have created and pushed the docker image to container registry.

But that is not the case at the moment. "mvn package" only builds the package and that's it. It's not creating any docker image. I guess we need to add jib plugin configurations inside kafka-to-bigquery's pom.xml.

### Beam Version

Newer than 2.43.0

**Comment by bvolpato** [comment]
We are revisiting the flow + documentation. Please use `mvn install` to build images for now. Also using https://github.com/GoogleCloudPlatform/DataflowTemplates#templates-plugin-beta may be helpful here.
