### ISSUE TITLE
[Feature Request]: Manage kafka offsets

### ISSUE THREAD

**Issue by ApurvaKusum** [GoogleCloudPlatform/DataflowTemplates#547]
### Related Template(s)

DataflowTemplate/v2/kafka-to-bigquery

### What feature(s) are you requesting?

Requesting feature to manage the Kafka offset ,so that we can have read exactly once per message , to avoid any redundancy in messages in case of pipeline failure.

**Comment by bvolpato** [comment]
This is related to the IO itself, not the Template. Please consider filing an issue at https://github.com/apache/beam/issues.
