### ISSUE TITLE
[Feature Request]: JdbcToBigQuery support parallel read

### ISSUE THREAD

**Issue by lveraszto** [GoogleCloudPlatform/DataflowTemplates#549]
### Related Template(s)

JdbcToBigQuery

### What feature(s) are you requesting?

Hi,

with the current implementation of this template, it does not support parallel read.

In the file it uses the `DynamicJdbcIO.<TableRow>read()` function and with this we can't increase the number of dataflows to make the reads parallel and so faster.

As a workaround we replaced this `DynamicJdbcIO` with the original `JdbcIO` and so we can use the `readWithPartitions()`. (In our case we don't need the dynamic driver class load. We upload the jar file to GCS and the template can found it)

With the `read()` our data was loaded in 16 hours with the parallel (more dataflow workers) version it was ~2 hour.

**Comment by bvolpato** [comment]
@lveraszto Thanks for reporting! We are planning to consolidate the implementations and leverage partitioned reads.

You're right that the blocker for now is the driver load, but Pranav is going to figure out a solution for us.

**Comment by pranavbhandari24** [comment]
https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/696 adds support for parallel reads in JdbcToBigQuery template.
