### ISSUE TITLE
[Feature Request]: Allow setting Splunk request metadata for PubSubToSplunk template

### ISSUE THREAD

**Issue by lanceblais** [GoogleCloudPlatform/DataflowTemplates#565]
### Related Template(s)

PubSubToSplunk

### What feature(s) are you requesting?

The JS UDFs that run on Nashorn are a non-starter for us as it requires too much additional engineering and it doesn't seem like we can use a more modern JS version.

As a result, we've moved to spinning up several dataflow jobs and using Splunk to map the HEC to a default index. 

What we'd like to do is set fields like Splunk Index, Source Type and other splunk metadata as Dataflow job fields. This way, we can still setup 1 Splunk HEC and use the dataflow metadata to route it to splunk properly.

I expect we can probably create our own dataflow template to do this, but I wanted to reach out here and ask first.

**Comment by bvolpato** [comment]
UDFs should accept ES6 as of December, if that helps.

I'll leave this as "needs triage" in case someone has the buffer to look at this. 

We also welcome contributions, in case you are looking for a balance between moving to a completely forked template.
