### ISSUE TITLE
Get rid of testBigQueryToBigTableLocallyWithEmulators unit test

### ISSUE THREAD

**Issue by nickuncaged1201** [GoogleCloudPlatform/DataflowTemplates#566]
### Related Template(s)

Syndeo templates

### What happened?

The test testBigQueryToBigTableLocallyWithEmulators is outdated. It will raise a type cast error when running.

### Beam Version

Newer than 2.43.0

**Comment by bvolpato** [comment]
@pabloem Want to take a look?
