### ISSUE TITLE
[Bug]: Cannot pull image "gcr.io/dataflow-templates-base/java11-template-launcher-base" using bitbucket-cloud pipeline. Container ID cannot be mapped to a host ID

### ISSUE THREAD

**Issue by usjanj02** [GoogleCloudPlatform/DataflowTemplates#569]
### Related Template(s)

gcr.io/dataflow-templates-base/java11-template-launcher-base:latest

### What happened?

When pulling the image "gcr.io/dataflow-templates-base/java11-template-launcher-base:latest" in bitbucket-cloud pipeline. getting error:
"**failed to register layer: Error processing tar file(exit status 1): Container ID 356666 cannot be mapped to a host ID**".

contacted atlassian support and they had us try a chown command - however, it was unsuccessful as we can not change permissions of files inside an image. (we do not own the image)

contacted google support and they confirmed the pull was successful using Cloud Build and GCloud Terminal. Suggested we create an issue on github

expected: the dockerfile would successfully build

### Beam Version

Newer than 2.43.0

### Relevant log output

```shell
Step 6/14 : FROM gcr.io/dataflow-templates-base/java11-template-launcher-base:latest
latest: Pulling from dataflow-templates-base/java11-template-launcher-base
c91f0b795ec7: Pulling fs layer
235a97f034f9: Pulling fs layer
501ed122cf77: Pulling fs layer
f138dfc92c78: Pulling fs layer
200eae7183e5: Pulling fs layer
7a4f8670a373: Pulling fs layer
e941fff8ce6e: Pulling fs layer
3adf8b2d90de: Pulling fs layer
a2790d533c88: Pulling fs layer
f138dfc92c78: Waiting
200eae7183e5: Waiting
7a4f8670a373: Waiting
e941fff8ce6e: Waiting
3adf8b2d90de: Waiting
a2790d533c88: Waiting
235a97f034f9: Verifying Checksum
235a97f034f9: Download complete
f138dfc92c78: Verifying Checksum
f138dfc92c78: Download complete
200eae7183e5: Verifying Checksum
200eae7183e5: Download complete
7a4f8670a373: Download complete
c91f0b795ec7: Verifying Checksum
c91f0b795ec7: Download complete
e941fff8ce6e: Download complete
a2790d533c88: Verifying Checksum
a2790d533c88: Download complete
3adf8b2d90de: Verifying Checksum
3adf8b2d90de: Download complete
501ed122cf77: Verifying Checksum
501ed122cf77: Download complete
c91f0b795ec7: Pull complete
235a97f034f9: Pull complete
failed to register layer: Error processing tar file(exit status 1): Container ID 356666 cannot be mapped to a host ID
```

**Comment by bvolpato** [comment]
Just `docker pull gcr.io/dataflow-templates-base/java11-template-launcher-base:latest` fails for you?

I tried here and it works. Please provide Dockerfile so we can try to reproduce?

Which OS / Docker version is being used?

**Comment by usjanj02** [comment]
Hi bvolpato - yes,

Debian GNU/Linux 11 (bullseye)
Docker version 20.10.22

the pipeline is running "docker build -f ./dataflow/Dockerfile -t $STAGE_IMAGE ."

here is the dockerfile: (doesnt have our build step. we have removed it to try and debug. breaks on FROM command)

FROM gcr.io/dataflow-templates-base/java11-template-launcher-base:latest

ARG WORKDIR=/template
ARG MAINCLASS=com.imgcp.dataflow.templates.PubsubToPostgresql
RUN mkdir -p ${WORKDIR}
WORKDIR ${WORKDIR}

COPY --from=build /app/target/google-cloud-dataflow-java-0.0.1-SNAPSHOT.jar /template/
RUN mkdir -p ${WORKDIR}/lib

ENV FLEX_TEMPLATE_JAVA_CLASSPATH=/template/google-cloud-dataflow-java-0.0.1-SNAPSHOT.jar
ENV FLEX_TEMPLATE_JAVA_MAIN_CLASS=${MAINCLASS}

**Comment by bvolpato** [comment]
It fails on the `from`?
I tried just 
```
FROM gcr.io/dataflow-templates-base/java11-template-launcher-base:latest

RUN echo "Building"
```

And it works fine for me on macOS and Debian.

![image](https://user-images.githubusercontent.com/3207647/215657228-99f8882b-534f-469d-8a03-21df32a2cedb.png)

**Comment by bvolpato** [comment]
This might help https://azureossd.github.io/2022/06/30/Docker-User-Namespace-remapping-issues/

**Comment by usjanj02** [comment]
Hi Bvolpato, yes it fails on the FROM. Im not sure if it has something to do with bitbucket-cloud being the run to run it?
from my understanding, we cant remap the file because we are not the owners of the image. cant break down which layer has the broken file to change.

![image](https://user-images.githubusercontent.com/102384132/215851004-406247a4-e896-4590-b7b6-fa5b501dd4bc.png)

**Comment by bvolpato** [comment]
I can see that we have ID 356666 in all files under `/usr/local/jdk-11-latest` which somehow is incompatible with your environment/OS.

However, I am not sure how to force smaller number during very specific build steps. I'm taking a look, though.

**Comment by bvolpato** [comment]
@usjanj02 Is this still a problem? We plan to offer alternatives to Debian as base images, and this might be fixed. Don't have a date yet, though

**Comment by usjanj02** [comment]
hi @bvolpato, thanks for investigating and offering future fix. for the time being, we have switched over to cloudbuild, as a means to get past this issue. Perhaps once the new base images are available, i can revisit
