### ISSUE TITLE
[Bug]: Does not build

### ISSUE THREAD

**Issue by chris-amor-street** [GoogleCloudPlatform/DataflowTemplates#570]
### Related Template(s)

Bigquery to Bigtable

### What happened?

Following the instructions in the README the mvn command fails with the following error:

Failed to execute goal on project dynamic-templates: Could not resolve dependencies for project com.google.cloud.teleport.v2:dynamic-templates:pom:1.0-SNAPSHOT: The following artifacts could not be resolved: com.google.cloud.teleport.metadata:metadata:jar:1.0-SNAPSHOT, com.google.cloud.teleport:integration-testing-lib:jar:1.0-SNAPSHOT, com.google.cloud.teleport:structured-logging:jar:1.0-SNAPSHOT, com.google.cloud.teleport:plaintext-logging:jar:1.0-SNAPSHOT: Could not find artifact com.google.cloud.teleport.metadata:metadata:jar:1.0-SNAPSHOT -> [Help 1]

### Beam Version

Newer than 2.43.0

### Relevant log output

```shell
Failed to execute goal on project dynamic-templates: Could not resolve dependencies for project com.google.cloud.teleport.v2:dynamic-templates:pom:1.0-SNAPSHOT: The following artifacts could not be resolved: com.google.cloud.teleport.metadata:metadata:jar:1.0-SNAPSHOT, com.google.cloud.teleport:integration-testing-lib:jar:1.0-SNAPSHOT, com.google.cloud.teleport:structured-logging:jar:1.0-SNAPSHOT, com.google.cloud.teleport:plaintext-logging:jar:1.0-SNAPSHOT: Could not find artifact com.google.cloud.teleport.metadata:metadata:jar:1.0-SNAPSHOT -> [Help 1]
```

**Comment by bvolpato** [comment]
Please give it a try trying to build from the parent folder (DataflowTemplates).

If you want a single module, you can use:

```
mvn clean install -pl v2/bigquery-to-bigtable -am`
```

**Comment by bvolpato** [comment]
@chris-amor-street did it work? can we close here?

**Comment by bvolpato** [comment]
This issue has been stale for some time now. Please reopen it if there is a follow up or related questions.
