### ISSUE TITLE
[Bug]: build and push image failed

### ISSUE THREAD

**Issue by michaelaltar** [GoogleCloudPlatform/DataflowTemplates#584]
### Related Template(s)

bigquery-to-bigtable

### What happened?

Running step "Build and push image to Google Container Repository from the v2 directory" failed. 
`mvn clean package \
    -Dimage=${TARGET_GCR_IMAGE} \
    -Dbase-container-image=${BASE_CONTAINER_IMAGE} \
    -Dbase-container-image.version=${BASE_CONTAINER_IMAGE_VERSION} \
    -Dapp-root=${APP_ROOT} \
    -Dcommand-spec=${COMMAND_SPEC} \
    -am -pl ${TEMPLATE_MODULE}`

### Beam Version

Newer than 2.43.0

### Relevant log output

```shell
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.16
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 16
[INFO] os.detected.classifier: osx-x86_64
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Google Cloud Teleport Dynamic                                      [pom]
[INFO] common                                                             [jar]
[INFO] bigquery-to-bigtable                                               [jar]
[INFO]
[INFO] -----------< com.google.cloud.teleport.v2:dynamic-templates >-----------
[INFO] Building Google Cloud Teleport Dynamic 1.0-SNAPSHOT                [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[WARNING] The POM for com.google.cloud.teleport:integration-testing-lib:jar:1.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.google.cloud.teleport:structured-logging:jar:1.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.google.cloud.teleport:plaintext-logging:jar:1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Google Cloud Teleport Dynamic 1.0-SNAPSHOT:
[INFO]
[INFO] Google Cloud Teleport Dynamic ...................... FAILURE [  0.593 s]
[INFO] common ............................................. SKIPPED
[INFO] bigquery-to-bigtable ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.220 s
[INFO] Finished at: 2023-02-09T15:46:41+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project dynamic-templates: Could not resolve dependencies for project com.google.cloud.teleport.v2:dynamic-templates:pom:1.0-SNAPSHOT: Failed to collect dependencies at com.google.cloud.teleport.metadata:metadata:jar:1.0-SNAPSHOT: Failed to read artifact descriptor for com.google.cloud.teleport.metadata:metadata:jar:1.0-SNAPSHOT: com.google.cloud.teleport:templates:pom:1.0-SNAPSHOT was not found in https://repo1.maven.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
```

**Comment by bvolpato** [comment]
I think we need to update the docs. You shouldn't run from the v2, but from the root, and include v2/ in the `-pl`.

I will keep this bug open to hear your feedback and track documentation updates.

**Comment by michaelaltar** [comment]
@bvolpato thanks, it seems to be working but I didn't see image in GCR
I run:
`mvn clean package \
    -Dimage=${TARGET_GCR_IMAGE} \
    -Dbase-container-image=${BASE_CONTAINER_IMAGE} \
    -Dbase-container-image.version=${BASE_CONTAINER_IMAGE_VERSION} \
    -Dapp-root=${APP_ROOT} \
    -Dcommand-spec=${COMMAND_SPEC} \
    -am -pl v2/${TEMPLATE_MODULE}`
and got:
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Google Cloud Dataflow Templates 1.0-SNAPSHOT:
[INFO]
[INFO] Google Cloud Dataflow Templates .................... SUCCESS [  0.678 s]
[INFO] Templates Metadata Module .......................... SUCCESS [  2.218 s]
[INFO] integration-testing-lib ............................ SUCCESS [ 20.303 s]
[INFO] structured-logging ................................. SUCCESS [  1.021 s]
[INFO] plaintext-logging .................................. SUCCESS [  0.071 s]
[INFO] Google Cloud Teleport Dynamic ...................... SUCCESS [ 15.440 s]
[INFO] common ............................................. SUCCESS [ 46.378 s]
[INFO] bigquery-to-bigtable ............................... SUCCESS [ 30.516 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:57 min
[INFO] Finished at: 2023-02-11T09:53:39+02:00
[INFO] ------------------------------------------------------------------------

but when I try to list images I got 
`echo $TARGET_GCR_IMAGE
gcr.io/dev-collection/insertion-bq-to-bt-01

gcloud container images list-tags gcr.io/dev-collection/${TARGET_GCR_IMAGE}
Listed 0 items.
`
May be I miss something? Sorry, I'm not so familiar with maven.

**Comment by bvolpato** [comment]
Try to use `install` instead of `package`. There were some recent changes.

**Comment by bvolpato** [comment]
Forgot to mention: I would recommend using https://github.com/GoogleCloudPlatform/DataflowTemplates#templates-plugin that should provide an easier way to stage or run templates.

**Comment by michaelaltar** [comment]
`install` still doesn't publishing image to GCR. I see this line in log that maybe related to an issue:
```
[INFO] Skipping containerization because packaging is 'pom'...
```
Anyway I'm closing the ticket, cause it seems too complex to me. Thanks.

**Comment by bvolpato** [comment]
@michaelaltar Give it a try to https://github.com/GoogleCloudPlatform/DataflowTemplates#templates-plugin, it should be considerably simpler. We are updating the docs to reflect those new changes.
