### ISSUE TITLE
[Bug]: Bigquery to Elastic template doesn't accept text transform UDF parameters

### ISSUE THREAD

**Issue by imranolas** [GoogleCloudPlatform/DataflowTemplates#637]
### Related Template(s)

BigQuery to Elasticsearch

### What happened?

The launch config doesn't accept the required parameters; `javascriptTextTransformGcsPath` or `javascriptTextTransformFunctionName`. Whilst the step does appear in the DAG but I can't see the configurable fields available in the Dataflow create job UI nor does the CLI accept the parameters.

I think it's just a case of missing fields in the metadata file.

re: https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/598

### Beam Version

Newer than 2.43.0

**Comment by bvolpato** [comment]
Thanks for bringing it up! I've reopened https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/598 and updated the status there, so we can keep the history.
