### ISSUE TITLE
[Bug]: Handling Duplicates in Google IoT Core QoS level 1 -> Pub/Sub to ElasticSearch

### ISSUE THREAD

**Issue by shermanericts** [GoogleCloudPlatform/DataflowTemplates#642]
### Related Template(s)

Pub/Sub to Elasticsearch

### What happened?

We are using the GCP [pubsub-to-elasticsearch](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/googlecloud-to-elasticsearch/docs/PubSubToElasticsearch/README.md) dataflow template for ingestion. 

----
1. We are getting messages such as this:
```
Error message from worker: java.io.IOException: Error writing to Elasticsearch, some elements could not be inserted:
Document id f4b8e5a630b65294e97eb22bdc745fcc59a0d4bf9766ba49e60117d9d322f4dc: [f4b8e5a630b65294e97eb22bdc745fcc59a0d4bf9766ba49e60117d9d322f4dc]: version conflict, document already exists (current version [1]) (version_conflict_engine_exception)
```

2. We set the `_id` field accordingly to guarantee uniqueness.
----

**ISSUE**  
* We are using IoT Core MQTT connections and Google only guarantees QoS level 1 (at least once delivery of a message) and NOT QoS level 2 (exactly once delivery of a message). 
* Thus, we can get duplicate messages in our queue. There's not really a way I can see to fingerprint uniqueness.

-----
We've tried to use the bulk Ingest API -> INDEX action instead of create, but data streams seem to like only op_type = CREATE.

I'm wondering if there's something I'm missing here. Any recommendations welcome.   [I saw this documentation](https://cloud.google.com/blog/products/data-analytics/handling-duplicate-data-in-streaming-pipeline-using-pubsub-dataflow) but not sure if that would handle our particular use case for duplicates at the IoT Core/MQTT level.

Thank you in advance!

Eric Sherman

### Beam Version

Newer than 2.43.0

### Relevant log output

```shell
Error message from worker: java.io.IOException: Error writing to Elasticsearch, some elements could not be inserted:
Document id f4b8e5a630b65294e97eb22bdc745fcc59a0d4bf9766ba49e60117d9d322f4dc: [f4b8e5a630b65294e97eb22bdc745fcc59a0d4bf9766ba49e60117d9d322f4dc]: version conflict, document already exists (current version [1]) (version_conflict_engine_exception)
```

**Comment by bvolpato** [comment]
Hi @shermanericts, yes I was going to recommend changing `bulkInsertMethod` to INDEX instead of CREATE. Are you getting the same errors?

**Comment by shermanericts** [comment]
> Hi @shermanericts, yes I was going to recommend changing `bulkInsertMethod` to INDEX instead of CREATE. Are you getting the same errors?

Right @bvolpato !  It's because we're using a data stream which only supports op_type of CREATE.   
Which leads me to another question:

If I use `default` for the namespace, the pubsub to elasticsearch dataflow job will create an index at `logs-gcp.pubsub-default`.  This essentially points to a data stream.

I guess a rookie question is how would one leverage a successful `bulkInsertMethod` if this defaults to using a data stream and data streams are `op_type create` only?

Thanks in advance!

**Comment by shermanericts** [comment]
Sorry.  Last thought.  In general, does the PubSub To Elasticsearch dataflow job ack messages in the subscription automatically?  In the analysis we see it doesn't seem to be doing that.  Is there anything special we need to set up in the Dataflow configuration to allow this?  The service account running the job has the access.

**Comment by shermanericts** [comment]
Actually, switching away from using data streams and going to write aliases that point to indicies + bulkInsertMethod to INDEX solved this.  closing
