### ISSUE TITLE
[Feature Request]: Use Secret Manager instead of plain secret input in MQTT to Pub/Sub template

### ISSUE THREAD

**Issue by damondouglas** [GoogleCloudPlatform/DataflowTemplates#664]
### Related Template(s)

MQTT to Pub/Sub template

### What feature(s) are you requesting?

Replace `password` template parameter with Secret Manager secret name.

Currently, the template optionally takes a `password` field in plaintext.  This feature request recommends calling for a Secret Manager secret instead.  This would require the Dataflow worker service account to have the IAM role roles/secretmanager.secretAccessor.

**Comment by shermanericts** [comment]
Similar to the PubsubToElasticSearch template using a secret from secret manager in lieu of `elasticsearchPassword`
