### ISSUE TITLE
[Bug]: Local build following readme results in OpenSSL error

### ISSUE THREAD

**Issue by pcgilday** [GoogleCloudPlatform/DataflowTemplates#678]
### Related Template(s)

Cloud_Datastream_To_BigQuery

### What happened?

I am trying to build a template and getting `java.lang.NoClassDefFoundError: org/conscrypt/OpenSSLProvider`. It's unclear if this is a bug, an issue with the README instructions, or user error on my part (apologies if it's the last one). 

I am building the template with the [staging templates](https://github.com/GoogleCloudPlatform/DataflowTemplates#staging-deploying-templates) docs:

```
mvn clean package -PtemplatesStage \
 -DskipTests \
 -DprojectId="<company-project>" \
 -DbucketName="gs://<company-bucket>" \
 -DstagePrefix="images/$(date +%Y*%m*%d)\_01" \
 -DtemplateName="Cloud_Datastream_To_BigQuery" \
 -pl v2/datastream-to-bigquery -am
```

This appears to build successfully, but does not deploy to my bucket I've specified, so I used the following command that I [found in the docs](https://cloud.google.com/dataflow/docs/guides/templates/using-flex-templates#create_a_flex_template). 

```
gcloud dataflow flex-template build gs://<company-bucket>/datastream-to-bigquery.json \
 --image-gcr-path "<artifact-registry>" \
 --sdk-language "JAVA" \
 --flex-template-base-image JAVA11 \
 --metadata-file "metadata.json" \
 --jar "target/datastream-to-bigquery-1.0-SNAPSHOT.jar" \
 --env FLEX_TEMPLATE_JAVA_MAIN_CLASS="com.google.cloud.teleport.v2.templates.DataStreamToBigQuery"
```

Everything looks good to this point, but when I run the job, I get the OpenSSL error mentioned above.

### Beam Version

Newer than 2.46.0

### Relevant log output

```shell
{
  "insertId": "4800712471473325515:155206:0:41351",
  "jsonPayload": {
    "line": "exec.go:66",
    "message": "java.lang.NoClassDefFoundError: org/conscrypt/OpenSSLProvider"
  },
  "resource": {
    "type": "dataflow_step",
    "labels": {
      "job_name": "datastream-cdc-dataflow-job-f0aa8fb",
      "job_id": "2023-05-08_11_08_15-16393896831592254474",
      "region": "us-east4",
      "project_id": "<company-project>",
      "step_id": ""
    }
  },
  "timestamp": "2023-05-08T18:14:49.846934Z",
  "severity": "INFO",
  "labels": {
    "compute.googleapis.com/resource_name": "datastream-cdc-datafl-05081110-tko8-harness-qzj3",
    "compute.googleapis.com/resource_type": "instance",
    "dataflow.googleapis.com/log_type": "system",
    "dataflow.googleapis.com/job_name": "datastream-cdc-dataflow-job-f0aa8fb",
    "dataflow.googleapis.com/job_id": "2023-05-08_11_08_15-16393896831592254474",
    "dataflow.googleapis.com/region": "us-east4",
    "compute.googleapis.com/resource_id": "4800712471473325515"
  },
  "logName": "projects/<company-project>/logs/dataflow.googleapis.com%2Fworker-startup",
  "receiveTimestamp": "2023-05-08T18:14:50.397145129Z"
}
```

**Comment by bvolpato** [comment]
Suggest checking the steps here: https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/datastream-to-bigquery/README_Cloud_Datastream_to_BigQuery.md

**Comment by meken** [comment]
Actually I'm experiencing exactly the same issue using a different template. If I follow the instructions from v2/kafka-to-pubsub README.md, I can create the template, and start running it. But the workers fail with the same error message as above. The generated kafka-to-pubsub-1.0-SNAPSHOT.jar doesn't contain the conscrypt classes.

**Comment by bvolpato** [comment]
@meken Thanks! `KafkaToPubsub` wasn't released as a proper template yet, so it wasn't annotated to use with the Templates plugin, so the suggestion above doesn't hold.

By default shading is excluding Conscrypt as it contains signatures / doesn't work properly (see https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/pom.xml#L523-L525). We'll have to package the Conscrypt JAR separately if the template is requiring it.

We can likely revisit the annotations to use the plugin, as it has this handling embedded.
