### ISSUE TITLE
Pubsub to BigQuery - Cumlated errors make jobs crash 

### ISSUE THREAD

**Issue by joseluisroblesurquiza** [GoogleCloudPlatform/DataflowTemplates#7]
Hi

I've been using Google Dataflow Templates to send messages from pub/sub to BigQuery based on this: https://cloud.google.com/dataflow/docs/templates/provided-templates#cloudpubsubtobigquery 

Since I've launched the dataflow job in streaming mode, the job has started to generate errors and finally crash based on the way Dataflow exceptions are handled:
https://cloud.google.com/dataflow/faq#how-are-java-exceptions-handled-in-cloud-dataflow

Here is the error:
java.lang.RuntimeException: java.io.IOException: Insert failed: [{"errors":[{"debugInfo":"","location":"","message":"Repeated record added outside of an array.","reason":"invalid"}],"index":0}, {"errors":[{"debugInfo":"","location":"","message":"","reason":"stopped"}],"index":1}, {"errors":[{"debugInfo":"","location":"","message":"","reason":"stopped"}],"index":2}, {"errors":[{"debugInfo":"","location":"","message":"","reason":"stopped"}],"index":3} .......]
        org.apache.beam.sdk.io.gcp.bigquery.StreamingWriteFn.flushRows(StreamingWriteFn.java:125)
        org.apache.beam.sdk.io.gcp.bigquery.StreamingWriteFn.finishBundle(StreamingWriteFn.java:94)

![captura de pantalla de 2018-09-13 13-54-58](https://user-images.githubusercontent.com/32904990/45486786-a224e000-b75c-11e8-8cf8-cbb153d691ab.png)

![image](https://user-images.githubusercontent.com/32904990/45486819-bf59ae80-b75c-11e8-809f-28b09521e9cf.png)

As I understand, this kind of behaviour makes this template not useful for data streaming.

Are there any possibilities to configure the template to avoid exceptions thrown but still send them to stackdriver?

Thanks

**Comment by ryanmcdowell** [comment]
The Pub/Sub to BigQuery template should handle parse, format, & UDF exceptions automatically by routing exceptions to a dead-letter table. However, in your case it looks like the failure is occurring on the output to BigQuery which is not being re-routed to the dead-letter today.

A couple of follow-up questions:
1) Which transform is throwing the errors (WriteSuccessfulRecords or WriteFailedRecords)?
2) Can you give a sample of the input? Sanitized as necessary.
3) Does the input schema match the BigQuery schema?
4) When you say the job crashed... are you just referring to the errors or did the job actually halt processing of records which should have been successful?

**Comment by joseluisroblesurquiza** [comment]
Hi Rayan

1. I'm not really sure but I think it could be in WriteFailedRecords because of the format of the JSON that DF is trying to cast from JSON to TableRow. Here is the complete message shown in Dataflow log (There isn't anything on GC Consle logging): [DF_ERROR.txt](https://github.com/GoogleCloudPlatform/DataflowTemplates/files/2383169/DF_ERROR.txt)

2. This file ([pub_sub_message.txt](https://github.com/GoogleCloudPlatform/DataflowTemplates/files/2383196/pub_sub_message.txt) ) is an example of the message sended to PUB/SUB
3. The JSON format match the BigQuery schema. The two first hours since the job starts, the information is correct in BQ, but after approx one or two hours the information stop to flow. 
4. The job is still working, but the information doesn't appear in BigQuery, maybe because of the system lag trying to process this exceptions
![image](https://user-images.githubusercontent.com/32904990/45548964-648c8980-b826-11e8-8006-1557d9167a66.png)

I look forward to your comments

**Comment by ryanmcdowell** [comment]
I tried to re-create the scenario with the provided payload but was unable to receive the same error. I used a pretty vanilla configuration in the "Create Job from Template" UI with no UDF, which consumed from a topic and output to a table ([schema](https://github.com/GoogleCloudPlatform/DataflowTemplates/files/2385349/support_schema.txt)). 

When publishing the message, I noticed that your payload is invalid JSON due to the trailing comma within the first record in the recommendations array. 

![support_invalid_json](https://user-images.githubusercontent.com/1460312/45582137-9110c780-b85f-11e8-9868-63bb23d97e49.png)



Considering the invalid JSON, the pipeline automatically routed the record to the dead-letter table which was successfully created and written to. I did not receive any errors on output.

![support_deadletter](https://user-images.githubusercontent.com/1460312/45582328-7db32b80-b862-11e8-980d-8f7436b280f9.png)

Is there anything you can think of that does not match between my test configuration and yours (e.g. UDF, custom code, etc)?

**Comment by joseluisroblesurquiza** [comment]
Sorry Rayan, my mistake, I tried to give you a reduce sample, but I'm sure that the JSON format is not the problem because of the code I'm using to generate PUBSUB messages (Python3):
![image](https://user-images.githubusercontent.com/32904990/45584317-9ad31300-b8d1-11e8-91ca-49518aabb42e.png)
![image](https://user-images.githubusercontent.com/32904990/45584319-ac1c1f80-b8d1-11e8-8d2b-b52cfa145c21.png)

If I'm right, this code ensure that the JSON will always be well format  (json.dumps(msg).encode()), otherwise I would receive an execution error before publishing the message. Anyway, I'm my case, I'm not receiving anything in the dead-letter table

If you need a complete PUBSUB message example or the BQ Schema, I would prefer to send them to you privately. If you need anything else from me, just ask for it. 

Thanks!

**Comment by joseluisroblesurquiza** [comment]
I just reproduce the error in an ad-hoc code. 

The error seems to be related to BigQueryServicesImplement (BigQueryServicesImpl.java:799)(BigQueryServicesImpl.java:813). Maybe is an exception you are not currently handling in your code... 
![image](https://user-images.githubusercontent.com/32904990/45618682-dd822000-ba76-11e8-8b79-3b88eb4da624.png)

I look forward to your comments

**Comment by ryanmcdowell** [comment]
I tried recreating the error, using NULL arrays, empty arrays, and populated arrays and was unable to do so. All were successfully output to the table. If you could send me an anonymized version of your payload / schema via email (in my profile), I can take a deeper look.

The error being thrown is from the BigQuery service invocation not liking the format of the JSON but I haven't been able to reproduce so it's difficult to pinpoint. A long-term solution will be to re-route records which failed output back to the dead-letter table. However, BigQueryIO does not give a description of the error which caused the failure so while that would get rid of the errors, it wouldn't give the user a good indication of why those records failed.

**Comment by mnebes** [comment]
Hi @ryanmcdowell, I am dealing with a similar problem here. If the message payload doesn't 100% match our BigQuery Schema it just keeps bouncing in the "WriteSuccessfulRecords" step. While we generally make sure we do not have such messages in the topic, when it unfortunately happens it is pretty annoying. 

We thought about a custom UDF to verify the json message schema, but it makes the template higher maintenance. We would definitely welcome a feature where the unsuccessful BigQuery writes would be re-routed to the dead-letter table if BigQuery returns a response indicating the payload is invalid.

**Comment by ryanmcdowell** [comment]
@mnebes - Thanks for the feedback. There should be a change for this in the next week or so.

**Comment by mnebes** [comment]
@ryanmcdowell That's awesome! Thank you very much!

**Comment by joseluisroblesurquiza** [comment]
Good News! Thanks you!

**Comment by mnebes** [comment]
Hi @ryanmcdowell , just wanted to ask if there are any news on this front?

**Comment by RyanGordon** [comment]
Also running into this bug with similar circumstances:
```Java.lang.RuntimeException: java.io.IOException: Insert failed: [{"errors":[{"debugInfo":"","location":"","message":"Maximum allowed row size exceeded. Allowed: 1048576 Row size: 1383816","reason":"invalid"}],"index":0}]```

The dataflow job retries indefinitely, causing the pipeline to stall out and not process anything else. In this case probably, the error should be logged & dropped

**Comment by mayansalama** [comment]
Hi there,

I'm encountering this issue when the schema of the incoming JSON message does not match the target table. @ryanmcdowell do you have any ideas if there's a fix for this on the way? I've included a stack trace below.

```
java.lang.RuntimeException: java.io.IOException: Insert failed: [{"errors":[{"debugInfo":"","location":"col3","message":"no such field.","reason":"invalid"}],"index":0}]
        org.apache.beam.sdk.io.gcp.bigquery.StreamingWriteFn.flushRows(StreamingWriteFn.java:141)
        org.apache.beam.sdk.io.gcp.bigquery.StreamingWriteFn.finishBundle(StreamingWriteFn.java:102)
Caused by: java.io.IOException: Insert failed: [{"errors":[{"debugInfo":"","location":"col3","message":"no such field.","reason":"invalid"}],"index":0}]
        org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$DatasetServiceImpl.insertAll(BigQueryServicesImpl.java:812)
        org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$DatasetServiceImpl.insertAll(BigQueryServicesImpl.java:829)
        org.apache.beam.sdk.io.gcp.bigquery.StreamingWriteFn.flushRows(StreamingWriteFn.java:130)
        org.apache.beam.sdk.io.gcp.bigquery.StreamingWriteFn.finishBundle(StreamingWriteFn.java:102)
        org.apache.beam.sdk.io.gcp.bigquery.StreamingWriteFn$DoFnInvoker.invokeFinishBundle(Unknown Source)
        org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.finishBundle(SimpleDoFnRunner.java:285)
        org.apache.beam.runners.dataflow.worker.SimpleParDoFn.finishBundle(SimpleParDoFn.java:407)
        org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.finish(ParDoOperation.java:56)
        org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:84)
        org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker.process(StreamingDataflowWorker.java:1233)
        org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker.access$1000(StreamingDataflowWorker.java:144)
        org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker$6.run(StreamingDataflowWorker.java:972)
        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        java.lang.Thread.run(Thread.java:745)
```
