### ISSUE TITLE
V2 Flex Templates are broken for Python

### ISSUE THREAD

**Issue by connorlwilkes** [GoogleCloudPlatform/DataflowTemplates#72]
When a flex template is created using both my own templates and the flex wordcount template provided the dataflow pipeline fails to build. The issue causes the dataflow pipeline to not build correctly once the API call is made.

I believe the issue arises from the base docker images found at: gcr.io/dataflow-templates-base

When I have tested these with: 

`docker run --interactive --tty gcr.io/dataflow-templates-base/java8-template-launcher-base bash`

I get the following error before it kicks me from the container and shuts it down:

```
2019/11/13 09:50:10 proto: duplicate proto type registered: google.api.Http
2019/11/13 09:50:10 proto: duplicate proto type registered: google.api.HttpRule
2019/11/13 09:50:10 proto: duplicate proto type registered: google.api.CustomHttpPattern
2019/11/13 09:50:10 proto: duplicate proto type registered: google.protobuf.FieldMask
Created new fluentd log writer for: /var/log/dataflow/template_launcher/runner-json.log
```

**Comment by sabhyankar** [comment]
Those are warnings that you can ignore and are not causing the pipeline to not build. It kicks you out of the container because the base has an entrypoint defined. 

Try:
`docker run -it --entrypoint=/bin/bash <yourContainerURI>`

**Comment by bvolpato** [comment]
+1 to Sameer's reply.

--

This issue has been stale for some time now. Please reopen it if there is a follow up or any related questions.
