### ISSUE TITLE
[Feature Request]: Compression support for Spanner to Text template

### ISSUE THREAD

**Issue by david-simplehash** [GoogleCloudPlatform/DataflowTemplates#722]
### Related Template(s)

SpannerToText

### What feature(s) are you requesting?

Template: https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/HEAD/v1/src/main/java/com/google/cloud/teleport/templates/SpannerToText.java

**Comment by bvolpato** [comment]
Will take a look at this, thanks for reporting.

Being a classic template, we are a bit limited on what we can do without ValueProviders for the suffix.

Did you consider customizing and building it? We have some easy to follow steps at  https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v1/README_Spanner_to_GCS_Text.md


Something like:
```
.withSuffix(".csv.gz")
.withCompression(Compression.GZIP)
```
