### ISSUE TITLE
Supporing AppProfileID in BigtableToAvro DataflowTemplate

### ISSUE THREAD

**Issue by daneshka** [GoogleCloudPlatform/DataflowTemplates#73]
We use BigtableToAvro to backup a huge Bigtable in production.
We have a replication on the BigTable. The main application connects to the Bigtable on one of the regions.
We want to force the backup process (BigtableToAvro) to use a specific Bigtable instance, which is in another region. 
The reason is we don't want to affect the main application performance.
This feature already exists in [Cloud Bigtable to Cloud Storage SequenceFile](https://cloud.google.com/dataflow/docs/guides/templates/provided-batch#cloud-bigtable-to-cloud-storage-sequencefile)

**Comment by bobo** [comment]
+1 Same reasons, really missing this when switching from the sequencefile job.
