### ISSUE TITLE
BigQuery to PubSub

### ISSUE THREAD

**Issue by adikul30** [GoogleCloudPlatform/DataflowTemplates#76]
Would BigQuery to PubSub be a good addition to these templates?
In the [Dataflow Codelab](https://codelabs.developers.google.com/codelabs/cloud-dataflow-nyc-taxi-tycoon), the NYC Taxi BigQuery dataset is used to publish to a topic. I think developers can utilize the existing, well-maintained BigQuery datasets to test out various streaming solutions through PubSub.

**Comment by sabhyankar** [comment]
That could be a template that we would be open to adding. Would you want to take a stab at putting it together and opening a PR? Let us know if you need some pointers.

**Comment by adikul30** [comment]
Hey! I actually got it to work a while ago but I'm not sure how to add unit testing as described in the CONTRIBUTING.md file. Pointers on that would be great.

**Comment by jaketf** [comment]
@adikul30 what sort of unit test guidance are you looking for? 
For general information on beam testing checkout the [docs](https://beam.apache.org/documentation/pipelines/test-your-pipeline/)

Could you look at [PubsubToBigQueryTest.java](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/src/test/java/com/google/cloud/teleport/templates/PubsubToBigQueryTest.java)
for inspiration / example and think about doing the inverse?
