### ISSUE TITLE
PubSub Subscription to BQ unable to set number of max workers

### ISSUE THREAD

**Issue by eduardchai** [GoogleCloudPlatform/DataflowTemplates#82]
Hi,

I created a dataflow job from `PubSub_Subscription_to_BigQuery` template and set the max number of worker to 10. The job was created successfully.  However, from the job details in GCP console, the `maxNumWorkers` is always reverted back to 3. Is there any workaround for this? Thanks!

PS: I have tried to create the job from UI and gcloud cli and was getting the same result.

**Comment by sabhyankar** [comment]
@melburnerodrigues - Can you take a look at this issue?
