### ISSUE TITLE
Add support for importing ARRAY, BYTES and STRUCT types into Spanner

### ISSUE THREAD

**Issue by githubwua** [GoogleCloudPlatform/DataflowTemplates#84]
Case comment in https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/src/main/java/com/google/cloud/teleport/spanner/TextImportPipeline.java mentions the following:

```
NOTE: BYTES, ARRAY, STRUCT types are not supported.
```

It is impossible to import tables containing one of these types.  The following exception error is thrown.

  "Unrecognized or unsupported column data type: ARRAY<STRING(20)>"

Can we please add support for these 3 code types?

**Comment by sabhyankar** [comment]
@melburnerodrigues - Can you take a look at this?

**Comment by ahmednofal** [comment]
any news regarding this issue ? Dataflow importing array values from csv is also failing with this error

Unrecognized column data type: ARRAY com.google.cloud.teleport.spanner.TextRowToMutation.parseRow(TextRowToMutation.java:248) com.google.cloud.teleport.spanner.TextRowToMutation.processElement(TextRowToMutation.java:119)

**Comment by lutherjohnrichards** [comment]
Hi, I am experiencing the same issue. Has there been any progress in this regard?
