### ISSUE TITLE
Specify project id for spanner to avro export

### ISSUE THREAD

**Issue by jlemaes** [GoogleCloudPlatform/DataflowTemplates#85]
I'd like to run the "Cloud Spanner to Cloud Storage Avro" template in a different project than the project my spanner instance lives. 
Currently I cannot specify the project in the template: https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/9a95f05b149cc99a6688c674596d8f4b0dcd5c35/src/main/java/com/google/cloud/teleport/spanner/ExportPipeline.java#L80-L84
It is however possible in the spanner to text export: https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/9a95f05b149cc99a6688c674596d8f4b0dcd5c35/src/main/java/com/google/cloud/teleport/templates/SpannerToText.java#L91-L95

Is this something that can be added?

**Comment by sabhyankar** [comment]
@melburnerodrigues - Can you take a look at this?
