### ISSUE TITLE
[Feature Request]: Python templates?

### ISSUE THREAD

**Issue by sergiomujica** [GoogleCloudPlatform/DataflowTemplates#892]
### Related Template(s)

all

### What feature(s) are you requesting?

Any chance to have a Python version of the templates?

**Comment by bvolpato** [comment]
We have a project to start supporting Python templates in the repository, but it's very unlikely that we'll provide every template. It's probably going to fill some gaps around AI / ML which is mostly only supported by Python / frameworks like Tensorflow or pytorch.

Can you be more specific on what you're expecting here?
