### ISSUE TITLE
 AutoValue_DynamicJdbcIO_DynamicRead.Builder

### ISSUE THREAD

**Issue by NayyarUnda** [GoogleCloudPlatform/DataflowTemplates#9]
Hi I have configured google cloud tools for eclipse and am facing this issue  after cloning Dataflow templates, I have added all these dependencies auto-service-1.0-rc1.jar, guava-16.0.1.jar, jsr-305-2.0.3.jar,auto-value-1.0-rc1.jar but could not resolve the issue  :AutoValue_DynamicJdbcIO_DynamicRead.Builder could not be resolved to a type

**Comment by NayyarUnda** [comment]
<img width="926" alt="screen shot 2018-10-01 at 11 51 38 pm" src="https://user-images.githubusercontent.com/22182939/46350163-0206fc00-c622-11e8-81b7-8026f54d818c.png">
Please let m eknow if anybody has a solution

**Comment by anznpatel** [comment]
I’ve encountered the same issue while trying to create a pipeline from Jdbc to BigQuery, any workarounds?

**Comment by sabhyankar** [comment]
@NayyarUnda Are you using Java 9 to compile this? Can you try with Java 8?

**Comment by ryanmcdowell** [comment]
Also, could you run `mvn clean compile` the `AutoValue` classes are generated during the `generate-sources` Maven lifecycle phase. Those classes should end up in target in a `generated-sources` folder.

**Comment by NayyarUnda** [comment]
> @NayyarUnda Are you using Java 9 to compile this? Can you try with Java 8?

@sabhyankar  I am using java 8 only

**Comment by anznpatel** [comment]
Can confirm it works for me now, using Java 8

**Comment by jpmauss** [comment]
@sabhyankar , I'm also running into this.  Any fix or suggestion besides manually creating the class and methods?

**Comment by yuvrajsingh79** [comment]
@NayyarUnda , I have manually created the classes and its methods but still not able to figure out the fix for this issue. Any suggestions , what I am missing out ?

**Comment by feliperandozup** [comment]
still facing errors here in the future :P

**Comment by chemburkartushar** [comment]
Anyone solutions to this issue?

**Comment by bvolpato** [comment]
Can you check if Preferences -> Java Compiler -> Annotation Processing is enabled?

In case it is already enabled, please check the existence of the folder `target/generated-sources/annotations`, and mark that directory as a Generated Sources Root.

**Comment by bvolpato** [comment]
This issue was stale for some time. Please reopen it if there is a follow up or any related questions.
