### ISSUE TITLE
DataFlow Template : Sequential BigQuery Table Insertion issue 

### ISSUE THREAD

**Issue by Rokshan2016** [GoogleCloudPlatform/DataflowTemplates#91]
@sabhyankar 

Hi , I am trying to create a dataflow template where it needs to write in two tables sequentially in bigquery.

e.g First it writes in "Patient" table. Ones its done then it writes in "Statistics" table. But I am facing this issue - once it writes in Patient table , it does not execution any code after that.

If you can please give some suggestion , it will be really helpful.

Thanks!

**Comment by sabhyankar** [comment]
Beam has a [WaitOn Transform](https://beam.apache.org/releases/javadoc/2.21.0/org/apache/beam/sdk/transforms/Wait.html) that allows you to sequence certain actions. However, this is not something we could currently use with BigQuery. I think, if you absolutely have to do sequencing, then perhaps using an external orchestration system such as Airflow or Cloud Composer might be the preferred approach.

I am curious about why you would want to write sequentially into two separate bigquery tables. This is generally a pattern that would be needed in a relational system with physical dependencies (Foreign keys for example). 

You could also re-post this on Beam's [StackOverflow](https://stackoverflow.com/questions/tagged/apache-beam) board to see if the community has a better approach
