### ISSUE TITLE
[Bug]: Double type Numbers are getting mis-converted for MongoDB to BigQuery

### ISSUE THREAD

**Issue by JoshAubrey** [GoogleCloudPlatform/DataflowTemplates#910]
### Related Template(s)

MongoDB to BigQuery

### What happened?

Hello there -
When batch loading from MongoDB Atlas, fields such as this, are ending up like this:

> As displayed in _MongoDB Compass_ application:
> ```
> fieldInMs Double:
> 1682380800000
> ```
> 
> As displayed in MongoDB Compass _export_ to JSON file:
> ```
>   "fieldInMs": {
>     "$numberLong": "1682380800000"
>   },
> ```

As displayed in the _source_data_ for the BigQuery Table: 
`"fieldInMs":1.6823808E12`

### Beam Version

Newer than 2.46.0

**Comment by bvolpato** [comment]
Seems like just scientific notation since `1.6823808E12` == `1682380800000`? Or you see it losing precision after some point?

**Comment by JoshAubrey** [comment]
Oh, I hadn't realized! I had only noticed the format seemed off, and figured something was happening like the other ticket I submitted for the foreign keys.
Is this expected behavior? (I'm new to BigQuery).
