### ISSUE TITLE
[Bug]: Database connections leak with Pubsub_to_JDBC template 

### ISSUE THREAD

**Issue by em-pe** [GoogleCloudPlatform/DataflowTemplates#945]
### Related Template(s)

Pubsub_to_Jdbc

### What happened?

Hi, I'm trying to use the template to get incoming Pubsub events stored in CloudSQL (MySQL) table. 

What I see is when there's spike in traffic the number of connections to database rapidly grows and stays high even though no new events are ingested in the process, like the job is not freeing the active connections. 

![Screenshot 2023-08-03 at 11 52 43](https://github.com/GoogleCloudPlatform/DataflowTemplates/assets/31856783/44ee153c-efc7-4a08-900b-aa1b373a508b)
![Screenshot 2023-08-03 at 11 53 35](https://github.com/GoogleCloudPlatform/DataflowTemplates/assets/31856783/99853f86-c429-432a-9aba-3467686371bb)

This eventually leads to errors with ConnectionFactory creation due to `Cannot create PoolableConnectionFactory (Could not create connection to database server. Attempted reconnect 3 times. Giving up.)`

Job config: 
```
driverClassName = com.mysql.jdbc.Driver
maxNumWorkers = 2
connectionProperties = unicode=true;characterEncoding=UTF-8;useSSL=true;autoReconnect=true;verifyServerCertificate=false
statement=INSERT INTO product (product_game_id,product_id,product_title,product_type,product_series_id,product_release_date,product_last_updated) VALUES (?,?,?,?,?,?,?)
```

Am I missing something like commit statement so that the connection stays open? I couldn't find the option to configure the size of connection pool as well so I'm wondering if that's a limitation of the template or connectionProperty I wasn't able to discover. I would be grateful for any help to make this setup work. 

### Beam Version

Newer than 2.46.0

### Relevant log output

```shell
java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up. org.apache.beam.runners.dataflow.worker.IntrinsicMapTaskExecutorFactory$1.typedApply(IntrinsicMapTaskExecutorFactory.java:178) org.apache.beam.runners.dataflow.worker.IntrinsicMapTaskExecutorFactory$1.typedApply(IntrinsicMapTaskExecutorFactory.java:149) org.apache.beam.runners.dataflow.worker.graph.Networks$TypeSafeNodeFunction.apply(Networks.java:67) org.apache.beam.runners.dataflow.worker.graph.Networks$TypeSafeNodeFunction.apply(Networks.java:54) org.apache.beam.runners.dataflow.worker.graph.Networks.replaceDirectedNetworkNodes(Networks.java:91) org.apache.beam.runners.dataflow.worker.IntrinsicMapTaskExecutorFactory.create(IntrinsicMapTaskExecutorFactory.java:109) org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker.process(StreamingDataflowWorker.java:1300) org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker.access$800(StreamingDataflowWorker.java:154) org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker$4.run(StreamingDataflowWorker.java:1044) org.apache.beam.runners.dataflow.worker.util.BoundedQueueExecutor.lambda$executeLockHeld$0(BoundedQueueExecutor.java:133) java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) java.base/java.lang.Thread.run(Thread.java:834) Caused by: org.apache.beam.sdk.util.UserCodeException: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up. 
...
```

**Comment by bvolpato** [comment]
Thanks for reporting! Can you try reducing `--numberOfWorkerHarnessThreads` (default is 300) and seeing if it lowers the # of connections?

We're looking into optimizing the connections, just want to verify if the boundary being seen here is based on the number of threads.

**Comment by em-pe** [comment]
Hi @bvolpato, I've run some variable traffic tests with `numberOfWorkerHarnessThreads` set to 50 and it indeed resulted in the stable number of around 50 database connections.

Since the main issue for me was going above the `max connections` limit resulting in broken connections and job errors, I can manage to fix it by lowering `numberOfWorkerHarnessThreads`, therefore feel free to close this issue.
