### ISSUE TITLE
[Bug]: Launcher image of individual template bundles too many jars

### ISSUE THREAD

**Issue by bijzz** [GoogleCloudPlatform/DataflowTemplates#950]
### Related Template(s)

BigQuery to BigTable

### What happened?

Hi,

for adjustments to the `bigquery-to-bigtable` template i am running

1. `mvn clean package -PtemplatesStage ...` command according to the `README.md` to build my own launcher image.
2. Triggering a run `gcloud dataflow flex-template run` according to the `README.md` to launch a run.

What i notice is that the container is build with more than 300 jars bundled in its `/template/bigquery-to-bigtable/*` subfolders. Accordingly, after a launch was initiated, the `filesToStage` list is a huge list of jars. This in turn likely causes slower startup times.

In contrast, when i make use of the already prebuild flex template of `bigquery-to-bigtable` the `filesToStage` parameter lists only two jar files (bigquery-to-bigtable-conscrypt.jar and bigquery-to-bigtable.jar). Is there something i can do to achieve the same with my own build?

### Beam Version

Newer than 2.46.0

**Comment by bvolpato** [comment]
Internally / during build time, the JARs are being shaded. It's not too clear if shading is better or not -- can you confirm faster startup times with it? 

In my experience it has been neutral / very little variance, just more noisy.

**Comment by bvolpato** [comment]
Thanks for reporting, though -- just trying to gather more information.
