### ISSUE TITLE
Issues in MySQL to BigQuery CDC template

### ISSUE THREAD

**Issue by rohansuri** [GoogleCloudPlatform/DataflowTemplates#98]
Thanks for the [CDC Dataflow template](https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/cdc-parent). I ran the template and faced a couple of issues. If they are valid, I'd be happy to submit a PR.

* In the properties file, `databaseName` should actually be named `instanceName` since it is used as Debezium's `database.server.name` property. 
* Discrepancy in PubSub Topic name. The [Deploying the connector](https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/cdc-parent#deploying-the-connector) section states:
  > A prefix for PubSub topics corresponding to each MySQL table. The connector will push table updates to ${PREFIX}${DB_INSTANCE}.${DATABASE}.${TABLE}
  
  i.e. the topic name is dot separated. Whereas later [Setting up PubSub topics](https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/cdc-parent#setting-up-pubsub-topics) section states it is underscore separated.
  > Table: my-mysql.cdc_demo.people
  Topic: export_demo_my-mysql_cdc_demo_people
  
  It happens to be dot separated actually as per the logic in [PubSubChangeConsumer.getPubsubTopicName](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/df388540006967b48aa56a6fecbb70f684778f55/v2/cdc-parent/cdc-embedded-connector/src/main/java/com/google/cloud/dataflow/cdc/connector/PubSubChangeConsumer.java#L88) since table name already is dot separated and there's no `String.replace` being done there to create the topic name underscore separated. So the docs in latter section needs a change.

* Order of dataset arguments passed to `MergeStatementBuildingFn` in [BigQueryChangeApplier](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/df388540006967b48aa56a6fecbb70f684778f55/v2/cdc-parent/cdc-change-applier/src/main/java/com/google/cloud/dataflow/cdc/applier/BigQueryChangeApplier.java#L147) is incorrect. `MergeStatementBuildingFn` [expects](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/df388540006967b48aa56a6fecbb70f684778f55/v2/cdc-parent/cdc-change-applier/src/main/java/com/google/cloud/dataflow/cdc/applier/MergeStatementBuildingFn.java#L59) `changeLogDataset` first.

**Comment by sabhyankar** [comment]
@pabloem

**Comment by pabloem** [comment]
thanks for catching these @rohansuri - PRs are very welcome!
